// GENERATED by scripts/fetch-province-attributes.mjs — do not edit.
//
// Solar and wind resource per province.
//
// solarCF is PV output per installed kWp at the optimal fixed tilt, divided by
// the hours in a year: a capacity factor measured rather than assumed, sampled
// at every amphoe and averaged by area. PVGIS
// puts Phetchaburi at 0.15 against the ~0.163 the season table in
// constants.ts implies. The annual level agrees well. The seasonal shape does
// not — see the note on solarByMonth.
//
// TRUST THESE TWO DIFFERENTLY.
//
// Solar is trustworthy. Cross-checked against NASA POWER, an independent
// satellite retrieval: the monthly curves agree at r = 0.955.
//
// It is sampled at every one of the 931 amphoe rather than once per province,
// which was not a refinement but a correction. A single centroid sample put
// Phetchaburi last of 77 for sunshine; its centroid lands in the Kaeng Krachan
// mountains, and the province's own amphoe run 0.147 there to 0.160 on the
// coastal plain — half the nationwide range inside one province. solarCFRange
// carries that spread so no one ranks provinces without seeing it.
//
// Wind is a floor, not an estimate. NASA POWER's grid is roughly 55 km, which
// is coarse enough that Phetchaburi contains two cells — measured, a point on
// the coast and a point 30 km away return identical numbers. Averaging over a
// cell that size flattens exactly the ridges and shorelines where turbines
// actually go, so the real resource at a real site is higher, by an amount
// this data cannot say. Use windMS50 to rank provinces, not to size a farm.
//
// The cross-province agreement between the two sources is only r = 0.668, so
// differences of ~0.01 in solarCF between neighbouring provinces are inside
// the noise and should not be read as real.
//
// Solar © European Union, PVGIS. Wind and irradiance from NASA POWER.
// Coastal flag derived from OpenStreetMap coastline data, ODbL.

export interface ProvinceResource {
  iso: string;
  /**
   * Annual PV capacity factor at optimal fixed tilt, area-weighted across the
   * province's amphoe.
   *
   * Sampled per amphoe rather than once at the province centre, because one
   * point is not enough: inside Phetchaburi alone PVGIS returns 0.147 in the
   * Kaeng Krachan mountains and 0.160 on the coastal plain, about half the
   * entire nationwide range from a single province. The centroid fell in the
   * mountains and made Phetchaburi look like the least sunny province in
   * Thailand, which it is not.
   */
  solarCF: number;
  /** Lowest and highest amphoe sample — how much solarCF is hiding. */
  solarCFRange: [number, number];
  /** Amphoe sampled for this province. */
  solarSamples: number;
  /**
   * Twelve monthly capacity factors, January first.
   *
   * The seasonal swing here is far gentler than the model assumes. Averaged
   * into the app's four seasons, Phetchaburi runs 1.6x from best to worst
   * where CF_BY_SEASON implies 4.4x, and nearly all of the gap is one season:
   * the table puts monsoon solar at 0.05 against 0.128 measured. The model is
   * sizing storage for a solar drought the satellites do not see.
   */
  solarByMonth: number[] | null;
  /** Tilt PVGIS chose, degrees — rises with latitude. */
  tiltDeg: number | null;
  /** Mean wind speed at 50 m, m/s. A ~55 km cell average; read as a floor. */
  windMS50: number;
  windByMonth: number[];
  /** Global horizontal irradiance, kWh/m²/day. */
  ghiKWhM2Day: number;
  /** Boundary comes within 3 km of the coastline. */
  coastal: boolean;
}

export const PROVINCE_RESOURCE: ProvinceResource[] = [
 {
  "iso": "TH-10",
  "solarCF": 0.164,
  "solarByMonth": [
   0.184,
   0.191,
   0.191,
   0.181,
   0.157,
   0.145,
   0.137,
   0.141,
   0.142,
   0.153,
   0.171,
   0.178
  ],
  "solarCFRange": [
   0.164,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 17,
  "windMS50": 4.28,
  "windByMonth": [
   4.02,
   4.22,
   4.46,
   4.3,
   4.23,
   4.72,
   4.87,
   4.82,
   3.9,
   3.38,
   4.01,
   4.44
  ],
  "ghiKWhM2Day": 5.23,
  "coastal": true
 },
 {
  "iso": "TH-11",
  "solarCF": 0.167,
  "solarByMonth": [
   0.186,
   0.195,
   0.196,
   0.185,
   0.16,
   0.148,
   0.14,
   0.145,
   0.146,
   0.154,
   0.171,
   0.18
  ],
  "solarCFRange": [
   0.166,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 17,
  "windMS50": 4.66,
  "windByMonth": [
   4.25,
   4.6,
   4.9,
   4.69,
   4.64,
   5.21,
   5.33,
   5.25,
   4.25,
   3.63,
   4.39,
   4.78
  ],
  "ghiKWhM2Day": 5.23,
  "coastal": true
 },
 {
  "iso": "TH-12",
  "solarCF": 0.163,
  "solarByMonth": [
   0.182,
   0.19,
   0.193,
   0.183,
   0.159,
   0.145,
   0.135,
   0.139,
   0.143,
   0.151,
   0.168,
   0.175
  ],
  "solarCFRange": [
   0.163,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 17,
  "windMS50": 4.28,
  "windByMonth": [
   4.02,
   4.22,
   4.46,
   4.3,
   4.23,
   4.72,
   4.87,
   4.82,
   3.9,
   3.38,
   4.01,
   4.44
  ],
  "ghiKWhM2Day": 5.23,
  "coastal": false
 },
 {
  "iso": "TH-13",
  "solarCF": 0.163,
  "solarByMonth": [
   0.182,
   0.189,
   0.19,
   0.18,
   0.156,
   0.144,
   0.136,
   0.139,
   0.141,
   0.152,
   0.171,
   0.177
  ],
  "solarCFRange": [
   0.162,
   0.165
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 4.28,
  "windByMonth": [
   4.02,
   4.22,
   4.46,
   4.3,
   4.23,
   4.72,
   4.87,
   4.82,
   3.9,
   3.38,
   4.01,
   4.44
  ],
  "ghiKWhM2Day": 5.22,
  "coastal": false
 },
 {
  "iso": "TH-14",
  "solarCF": 0.163,
  "solarByMonth": [
   0.182,
   0.188,
   0.191,
   0.181,
   0.157,
   0.145,
   0.135,
   0.138,
   0.142,
   0.153,
   0.171,
   0.176
  ],
  "solarCFRange": [
   0.163,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 4.37,
  "windByMonth": [
   4.27,
   4.23,
   4.43,
   4.25,
   4.23,
   4.78,
   4.95,
   4.81,
   3.79,
   3.58,
   4.33,
   4.81
  ],
  "ghiKWhM2Day": 5.22,
  "coastal": false
 },
 {
  "iso": "TH-15",
  "solarCF": 0.164,
  "solarByMonth": [
   0.184,
   0.19,
   0.191,
   0.182,
   0.157,
   0.144,
   0.134,
   0.136,
   0.142,
   0.154,
   0.172,
   0.178
  ],
  "solarCFRange": [
   0.163,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 4.37,
  "windByMonth": [
   4.27,
   4.23,
   4.43,
   4.25,
   4.23,
   4.78,
   4.95,
   4.81,
   3.79,
   3.58,
   4.33,
   4.81
  ],
  "ghiKWhM2Day": 5.22,
  "coastal": false
 },
 {
  "iso": "TH-16",
  "solarCF": 0.166,
  "solarByMonth": [
   0.188,
   0.193,
   0.192,
   0.182,
   0.159,
   0.146,
   0.137,
   0.137,
   0.145,
   0.157,
   0.176,
   0.184
  ],
  "solarCFRange": [
   0.165,
   0.167
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 4.63,
  "windByMonth": [
   4.74,
   4.48,
   4.61,
   4.37,
   4.35,
   5.01,
   5.13,
   4.87,
   3.74,
   4.03,
   4.82,
   5.37
  ],
  "ghiKWhM2Day": 5.21,
  "coastal": false
 },
 {
  "iso": "TH-17",
  "solarCF": 0.165,
  "solarByMonth": [
   0.186,
   0.192,
   0.192,
   0.183,
   0.159,
   0.144,
   0.134,
   0.135,
   0.144,
   0.155,
   0.173,
   0.18
  ],
  "solarCFRange": [
   0.164,
   0.165
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 4.63,
  "windByMonth": [
   4.74,
   4.48,
   4.61,
   4.37,
   4.35,
   5.01,
   5.13,
   4.87,
   3.74,
   4.03,
   4.82,
   5.37
  ],
  "ghiKWhM2Day": 5.22,
  "coastal": false
 },
 {
  "iso": "TH-18",
  "solarCF": 0.163,
  "solarByMonth": [
   0.187,
   0.193,
   0.192,
   0.182,
   0.157,
   0.141,
   0.129,
   0.131,
   0.143,
   0.151,
   0.17,
   0.178
  ],
  "solarCFRange": [
   0.162,
   0.165
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 4.08,
  "windByMonth": [
   3.79,
   3.65,
   3.84,
   3.86,
   3.94,
   4.6,
   4.79,
   4.63,
   3.59,
   3.52,
   4.16,
   4.5
  ],
  "ghiKWhM2Day": 5.21,
  "coastal": false
 },
 {
  "iso": "TH-19",
  "solarCF": 0.162,
  "solarByMonth": [
   0.182,
   0.187,
   0.189,
   0.179,
   0.155,
   0.141,
   0.133,
   0.134,
   0.138,
   0.152,
   0.173,
   0.179
  ],
  "solarCFRange": [
   0.161,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 4.24,
  "windByMonth": [
   4.34,
   3.9,
   3.96,
   3.65,
   3.87,
   4.5,
   4.74,
   4.64,
   3.64,
   3.8,
   4.67,
   5.09
  ],
  "ghiKWhM2Day": 5.01,
  "coastal": false
 },
 {
  "iso": "TH-20",
  "solarCF": 0.164,
  "solarByMonth": [
   0.185,
   0.189,
   0.187,
   0.177,
   0.153,
   0.144,
   0.139,
   0.145,
   0.14,
   0.152,
   0.174,
   0.183
  ],
  "solarCFRange": [
   0.158,
   0.177
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 4.81,
  "windByMonth": [
   4.25,
   4.29,
   4.54,
   4.27,
   4.79,
   5.66,
   5.9,
   5.82,
   4.71,
   3.82,
   4.61,
   5.01
  ],
  "ghiKWhM2Day": 4.96,
  "coastal": true
 },
 {
  "iso": "TH-21",
  "solarCF": 0.165,
  "solarByMonth": [
   0.187,
   0.191,
   0.188,
   0.177,
   0.151,
   0.143,
   0.139,
   0.148,
   0.141,
   0.154,
   0.176,
   0.185
  ],
  "solarCFRange": [
   0.161,
   0.173
  ],
  "solarSamples": 6,
  "tiltDeg": 17,
  "windMS50": 4.81,
  "windByMonth": [
   4.25,
   4.29,
   4.54,
   4.27,
   4.79,
   5.66,
   5.9,
   5.82,
   4.71,
   3.82,
   4.61,
   5.01
  ],
  "ghiKWhM2Day": 5.07,
  "coastal": true
 },
 {
  "iso": "TH-22",
  "solarCF": 0.159,
  "solarByMonth": [
   0.186,
   0.187,
   0.182,
   0.17,
   0.144,
   0.133,
   0.129,
   0.136,
   0.133,
   0.15,
   0.174,
   0.184
  ],
  "solarCFRange": [
   0.156,
   0.166
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 3.55,
  "windByMonth": [
   3.36,
   3.23,
   3.35,
   3.08,
   3.48,
   3.99,
   4.16,
   4.15,
   3.41,
   2.96,
   3.51,
   3.85
  ],
  "ghiKWhM2Day": 4.74,
  "coastal": true
 },
 {
  "iso": "TH-23",
  "solarCF": 0.156,
  "solarByMonth": [
   0.186,
   0.188,
   0.182,
   0.17,
   0.14,
   0.125,
   0.119,
   0.127,
   0.126,
   0.147,
   0.173,
   0.184
  ],
  "solarCFRange": [
   0.152,
   0.167
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 3.24,
  "windByMonth": [
   2.93,
   2.72,
   2.82,
   2.63,
   3.11,
   3.68,
   3.95,
   4.08,
   3.35,
   2.73,
   3.24,
   3.54
  ],
  "ghiKWhM2Day": 4.74,
  "coastal": true
 },
 {
  "iso": "TH-24",
  "solarCF": 0.16,
  "solarByMonth": [
   0.18,
   0.185,
   0.183,
   0.173,
   0.15,
   0.14,
   0.135,
   0.14,
   0.136,
   0.151,
   0.171,
   0.178
  ],
  "solarCFRange": [
   0.158,
   0.166
  ],
  "solarSamples": 6,
  "tiltDeg": 17,
  "windMS50": 4.71,
  "windByMonth": [
   4.39,
   4.4,
   4.62,
   4.33,
   4.67,
   5.41,
   5.59,
   5.49,
   4.41,
   3.74,
   4.51,
   4.95
  ],
  "ghiKWhM2Day": 4.96,
  "coastal": true
 },
 {
  "iso": "TH-25",
  "solarCF": 0.162,
  "solarByMonth": [
   0.186,
   0.19,
   0.187,
   0.176,
   0.152,
   0.139,
   0.133,
   0.136,
   0.137,
   0.153,
   0.174,
   0.183
  ],
  "solarCFRange": [
   0.159,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 4.39,
  "windByMonth": [
   4.56,
   3.87,
   3.81,
   3.41,
   3.87,
   4.7,
   5.02,
   4.98,
   3.94,
   3.98,
   5,
   5.46
  ],
  "ghiKWhM2Day": 5.01,
  "coastal": false
 },
 {
  "iso": "TH-26",
  "solarCF": 0.159,
  "solarByMonth": [
   0.181,
   0.186,
   0.185,
   0.175,
   0.15,
   0.137,
   0.129,
   0.131,
   0.134,
   0.15,
   0.171,
   0.178
  ],
  "solarCFRange": [
   0.159,
   0.16
  ],
  "solarSamples": 4,
  "tiltDeg": 19,
  "windMS50": 4.29,
  "windByMonth": [
   4.36,
   3.95,
   4.03,
   3.74,
   3.99,
   4.61,
   4.8,
   4.73,
   3.86,
   3.67,
   4.57,
   5.08
  ],
  "ghiKWhM2Day": 5.01,
  "coastal": false
 },
 {
  "iso": "TH-27",
  "solarCF": 0.164,
  "solarByMonth": [
   0.188,
   0.192,
   0.186,
   0.177,
   0.155,
   0.142,
   0.136,
   0.141,
   0.141,
   0.155,
   0.173,
   0.182
  ],
  "solarCFRange": [
   0.161,
   0.165
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 4.39,
  "windByMonth": [
   4.49,
   3.93,
   3.86,
   3.52,
   3.93,
   4.74,
   5.1,
   5.06,
   3.98,
   3.9,
   4.82,
   5.27
  ],
  "ghiKWhM2Day": 5.04,
  "coastal": false
 },
 {
  "iso": "TH-30",
  "solarCF": 0.163,
  "solarByMonth": [
   0.188,
   0.192,
   0.189,
   0.178,
   0.155,
   0.141,
   0.133,
   0.134,
   0.138,
   0.153,
   0.173,
   0.183
  ],
  "solarCFRange": [
   0.16,
   0.167
  ],
  "solarSamples": 6,
  "tiltDeg": 20,
  "windMS50": 4.85,
  "windByMonth": [
   4.74,
   4.39,
   4.47,
   4.17,
   4.46,
   5.38,
   5.79,
   5.67,
   4.29,
   4.36,
   5.04,
   5.42
  ],
  "ghiKWhM2Day": 5.11,
  "coastal": false
 },
 {
  "iso": "TH-31",
  "solarCF": 0.165,
  "solarByMonth": [
   0.191,
   0.196,
   0.189,
   0.178,
   0.157,
   0.145,
   0.138,
   0.139,
   0.141,
   0.157,
   0.172,
   0.183
  ],
  "solarCFRange": [
   0.164,
   0.167
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 4.99,
  "windByMonth": [
   5.38,
   4.67,
   4.36,
   4.03,
   4.39,
   5.34,
   5.67,
   5.49,
   4.23,
   4.58,
   5.54,
   6.12
  ],
  "ghiKWhM2Day": 5.11,
  "coastal": false
 },
 {
  "iso": "TH-32",
  "solarCF": 0.167,
  "solarByMonth": [
   0.193,
   0.197,
   0.192,
   0.181,
   0.159,
   0.145,
   0.137,
   0.137,
   0.14,
   0.16,
   0.176,
   0.185
  ],
  "solarCFRange": [
   0.166,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 5.04,
  "windByMonth": [
   5.56,
   4.84,
   4.41,
   4,
   4.36,
   5.37,
   5.68,
   5.47,
   4.21,
   4.61,
   5.66,
   6.31
  ],
  "ghiKWhM2Day": 5.2,
  "coastal": false
 },
 {
  "iso": "TH-33",
  "solarCF": 0.165,
  "solarByMonth": [
   0.192,
   0.197,
   0.191,
   0.179,
   0.156,
   0.141,
   0.134,
   0.135,
   0.135,
   0.156,
   0.175,
   0.184
  ],
  "solarCFRange": [
   0.163,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 4.89,
  "windByMonth": [
   5.45,
   4.8,
   4.36,
   3.88,
   4.14,
   5.13,
   5.49,
   5.27,
   4.03,
   4.43,
   5.49,
   6.17
  ],
  "ghiKWhM2Day": 5.19,
  "coastal": false
 },
 {
  "iso": "TH-34",
  "solarCF": 0.165,
  "solarByMonth": [
   0.195,
   0.2,
   0.194,
   0.18,
   0.154,
   0.139,
   0.129,
   0.131,
   0.135,
   0.159,
   0.177,
   0.186
  ],
  "solarCFRange": [
   0.163,
   0.166
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 4.65,
  "windByMonth": [
   5.2,
   4.65,
   4.28,
   3.78,
   3.84,
   4.68,
   5.04,
   4.87,
   3.84,
   4.31,
   5.34,
   5.94
  ],
  "ghiKWhM2Day": 5.03,
  "coastal": false
 },
 {
  "iso": "TH-35",
  "solarCF": 0.168,
  "solarByMonth": [
   0.196,
   0.2,
   0.194,
   0.182,
   0.157,
   0.144,
   0.134,
   0.133,
   0.141,
   0.165,
   0.178,
   0.189
  ],
  "solarCFRange": [
   0.168,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 21,
  "windMS50": 5.07,
  "windByMonth": [
   6.05,
   5.37,
   4.73,
   4.19,
   4.13,
   4.97,
   5.17,
   4.9,
   3.88,
   4.98,
   5.86,
   6.52
  ],
  "ghiKWhM2Day": 5.22,
  "coastal": false
 },
 {
  "iso": "TH-36",
  "solarCF": 0.166,
  "solarByMonth": [
   0.192,
   0.199,
   0.195,
   0.183,
   0.157,
   0.14,
   0.129,
   0.129,
   0.141,
   0.159,
   0.179,
   0.188
  ],
  "solarCFRange": [
   0.163,
   0.169
  ],
  "solarSamples": 6,
  "tiltDeg": 21,
  "windMS50": 4.67,
  "windByMonth": [
   4.88,
   4.28,
   4.22,
   3.84,
   4.02,
   5,
   5.33,
   5.11,
   3.8,
   4.58,
   5.27,
   5.63
  ],
  "ghiKWhM2Day": 4.9,
  "coastal": false
 },
 {
  "iso": "TH-37",
  "solarCF": 0.167,
  "solarByMonth": [
   0.196,
   0.201,
   0.195,
   0.182,
   0.157,
   0.143,
   0.132,
   0.131,
   0.14,
   0.164,
   0.177,
   0.189
  ],
  "solarCFRange": [
   0.166,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 20,
  "windMS50": 4.95,
  "windByMonth": [
   5.89,
   5.25,
   4.65,
   4.12,
   4.06,
   4.85,
   5.07,
   4.78,
   3.81,
   4.8,
   5.7,
   6.35
  ],
  "ghiKWhM2Day": 5.22,
  "coastal": false
 },
 {
  "iso": "TH-38",
  "solarCF": 0.16,
  "solarByMonth": [
   0.189,
   0.194,
   0.189,
   0.176,
   0.142,
   0.126,
   0.117,
   0.116,
   0.138,
   0.167,
   0.183,
   0.187
  ],
  "solarCFRange": [
   0.157,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 24,
  "windMS50": 3.9,
  "windByMonth": [
   4.23,
   3.89,
   3.77,
   3.55,
   3.46,
   3.94,
   4.01,
   3.72,
   3.14,
   3.99,
   4.35,
   4.73
  ],
  "ghiKWhM2Day": 4.7,
  "coastal": false
 },
 {
  "iso": "TH-39",
  "solarCF": 0.162,
  "solarByMonth": [
   0.186,
   0.195,
   0.189,
   0.176,
   0.151,
   0.136,
   0.126,
   0.127,
   0.143,
   0.159,
   0.175,
   0.182
  ],
  "solarCFRange": [
   0.161,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 22,
  "windMS50": 4.38,
  "windByMonth": [
   4.79,
   4.43,
   4.32,
   4.11,
   3.89,
   4.5,
   4.55,
   4.33,
   3.56,
   4.25,
   4.67,
   5.17
  ],
  "ghiKWhM2Day": 5,
  "coastal": false
 },
 {
  "iso": "TH-40",
  "solarCF": 0.166,
  "solarByMonth": [
   0.19,
   0.198,
   0.191,
   0.18,
   0.159,
   0.144,
   0.133,
   0.133,
   0.145,
   0.161,
   0.175,
   0.184
  ],
  "solarCFRange": [
   0.164,
   0.167
  ],
  "solarSamples": 6,
  "tiltDeg": 20,
  "windMS50": 4.65,
  "windByMonth": [
   4.96,
   4.48,
   4.39,
   4.13,
   4.14,
   4.92,
   5.03,
   4.78,
   3.76,
   4.51,
   5.1,
   5.57
  ],
  "ghiKWhM2Day": 5.06,
  "coastal": false
 },
 {
  "iso": "TH-41",
  "solarCF": 0.163,
  "solarByMonth": [
   0.189,
   0.198,
   0.191,
   0.177,
   0.15,
   0.135,
   0.127,
   0.126,
   0.142,
   0.162,
   0.179,
   0.185
  ],
  "solarCFRange": [
   0.161,
   0.167
  ],
  "solarSamples": 6,
  "tiltDeg": 22,
  "windMS50": 4.66,
  "windByMonth": [
   5.24,
   4.87,
   4.61,
   4.31,
   4.11,
   4.71,
   4.76,
   4.46,
   3.69,
   4.56,
   5,
   5.52
  ],
  "ghiKWhM2Day": 5,
  "coastal": false
 },
 {
  "iso": "TH-42",
  "solarCF": 0.16,
  "solarByMonth": [
   0.186,
   0.195,
   0.192,
   0.18,
   0.151,
   0.131,
   0.121,
   0.12,
   0.137,
   0.155,
   0.175,
   0.182
  ],
  "solarCFRange": [
   0.157,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 23,
  "windMS50": 4,
  "windByMonth": [
   3.95,
   3.96,
   4.08,
   3.91,
   3.75,
   4.47,
   4.65,
   4.45,
   3.46,
   3.57,
   3.65,
   4.01
  ],
  "ghiKWhM2Day": 4.86,
  "coastal": false
 },
 {
  "iso": "TH-43",
  "solarCF": 0.162,
  "solarByMonth": [
   0.188,
   0.197,
   0.19,
   0.177,
   0.146,
   0.131,
   0.124,
   0.122,
   0.141,
   0.164,
   0.18,
   0.184
  ],
  "solarCFRange": [
   0.158,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 23,
  "windMS50": 3.98,
  "windByMonth": [
   4.38,
   4.13,
   3.99,
   3.68,
   3.52,
   3.97,
   4.03,
   3.78,
   3.23,
   4.02,
   4.32,
   4.67
  ],
  "ghiKWhM2Day": 5,
  "coastal": false
 },
 {
  "iso": "TH-44",
  "solarCF": 0.168,
  "solarByMonth": [
   0.192,
   0.199,
   0.193,
   0.182,
   0.161,
   0.146,
   0.136,
   0.135,
   0.145,
   0.162,
   0.176,
   0.186
  ],
  "solarCFRange": [
   0.167,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 20,
  "windMS50": 5.13,
  "windByMonth": [
   5.72,
   5.07,
   4.67,
   4.26,
   4.43,
   5.38,
   5.59,
   5.29,
   4.07,
   4.93,
   5.78,
   6.34
  ],
  "ghiKWhM2Day": 5.22,
  "coastal": false
 },
 {
  "iso": "TH-45",
  "solarCF": 0.168,
  "solarByMonth": [
   0.195,
   0.2,
   0.193,
   0.182,
   0.159,
   0.145,
   0.135,
   0.134,
   0.143,
   0.165,
   0.178,
   0.188
  ],
  "solarCFRange": [
   0.168,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 20,
  "windMS50": 5.15,
  "windByMonth": [
   5.98,
   5.28,
   4.71,
   4.24,
   4.32,
   5.24,
   5.44,
   5.15,
   3.99,
   5.01,
   5.88,
   6.54
  ],
  "ghiKWhM2Day": 5.22,
  "coastal": false
 },
 {
  "iso": "TH-46",
  "solarCF": 0.168,
  "solarByMonth": [
   0.195,
   0.201,
   0.194,
   0.182,
   0.157,
   0.143,
   0.133,
   0.133,
   0.144,
   0.165,
   0.18,
   0.188
  ],
  "solarCFRange": [
   0.167,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 21,
  "windMS50": 5.12,
  "windByMonth": [
   6.03,
   5.38,
   4.84,
   4.36,
   4.3,
   5.07,
   5.17,
   4.89,
   3.94,
   5.1,
   5.86,
   6.48
  ],
  "ghiKWhM2Day": 5.09,
  "coastal": false
 },
 {
  "iso": "TH-47",
  "solarCF": 0.165,
  "solarByMonth": [
   0.194,
   0.199,
   0.192,
   0.179,
   0.149,
   0.135,
   0.126,
   0.125,
   0.141,
   0.167,
   0.183,
   0.189
  ],
  "solarCFRange": [
   0.164,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 23,
  "windMS50": 4.65,
  "windByMonth": [
   5.11,
   4.75,
   4.53,
   4.27,
   4.15,
   4.81,
   4.92,
   4.57,
   3.68,
   4.58,
   4.97,
   5.45
  ],
  "ghiKWhM2Day": 5.03,
  "coastal": false
 },
 {
  "iso": "TH-48",
  "solarCF": 0.164,
  "solarByMonth": [
   0.195,
   0.199,
   0.192,
   0.179,
   0.15,
   0.135,
   0.125,
   0.124,
   0.14,
   0.164,
   0.18,
   0.189
  ],
  "solarCFRange": [
   0.162,
   0.167
  ],
  "solarSamples": 6,
  "tiltDeg": 22,
  "windMS50": 4.16,
  "windByMonth": [
   4.66,
   4.32,
   4.11,
   3.82,
   3.67,
   4.18,
   4.26,
   3.95,
   3.29,
   4.15,
   4.54,
   4.96
  ],
  "ghiKWhM2Day": 4.87,
  "coastal": false
 },
 {
  "iso": "TH-49",
  "solarCF": 0.167,
  "solarByMonth": [
   0.196,
   0.2,
   0.194,
   0.182,
   0.155,
   0.142,
   0.131,
   0.131,
   0.142,
   0.164,
   0.176,
   0.188
  ],
  "solarCFRange": [
   0.166,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 21,
  "windMS50": 5,
  "windByMonth": [
   5.87,
   5.33,
   4.79,
   4.29,
   4.18,
   4.92,
   5.06,
   4.74,
   3.88,
   5.03,
   5.68,
   6.23
  ],
  "ghiKWhM2Day": 5.05,
  "coastal": false
 },
 {
  "iso": "TH-50",
  "solarCF": 0.157,
  "solarByMonth": [
   0.195,
   0.21,
   0.204,
   0.18,
   0.14,
   0.113,
   0.101,
   0.104,
   0.129,
   0.153,
   0.177,
   0.185
  ],
  "solarCFRange": [
   0.155,
   0.162
  ],
  "solarSamples": 6,
  "tiltDeg": 26,
  "windMS50": 2.06,
  "windByMonth": [
   1.95,
   2.3,
   2.5,
   2.34,
   2.15,
   2.26,
   2.19,
   2.04,
   1.78,
   1.72,
   1.73,
   1.79
  ],
  "ghiKWhM2Day": 4.8,
  "coastal": false
 },
 {
  "iso": "TH-51",
  "solarCF": 0.159,
  "solarByMonth": [
   0.187,
   0.205,
   0.201,
   0.181,
   0.145,
   0.124,
   0.115,
   0.116,
   0.135,
   0.149,
   0.171,
   0.178
  ],
  "solarCFRange": [
   0.158,
   0.16
  ],
  "solarSamples": 6,
  "tiltDeg": 23,
  "windMS50": 2.94,
  "windByMonth": [
   2.45,
   2.95,
   3.25,
   3.09,
   3.03,
   3.76,
   3.86,
   3.56,
   2.57,
   2.21,
   2.22,
   2.28
  ],
  "ghiKWhM2Day": 4.8,
  "coastal": false
 },
 {
  "iso": "TH-52",
  "solarCF": 0.158,
  "solarByMonth": [
   0.182,
   0.201,
   0.199,
   0.182,
   0.146,
   0.127,
   0.116,
   0.116,
   0.135,
   0.148,
   0.168,
   0.174
  ],
  "solarCFRange": [
   0.156,
   0.159
  ],
  "solarSamples": 6,
  "tiltDeg": 23,
  "windMS50": 2.75,
  "windByMonth": [
   2.55,
   2.75,
   3.03,
   3.01,
   2.86,
   3.14,
   3.06,
   2.82,
   2.3,
   2.3,
   2.47,
   2.68
  ],
  "ghiKWhM2Day": 4.94,
  "coastal": false
 },
 {
  "iso": "TH-53",
  "solarCF": 0.161,
  "solarByMonth": [
   0.185,
   0.197,
   0.197,
   0.183,
   0.15,
   0.132,
   0.121,
   0.12,
   0.14,
   0.158,
   0.176,
   0.18
  ],
  "solarCFRange": [
   0.161,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 23,
  "windMS50": 3.2,
  "windByMonth": [
   3.31,
   3.13,
   3.26,
   3.21,
   3,
   3.45,
   3.47,
   3.27,
   2.54,
   2.9,
   3.19,
   3.58
  ],
  "ghiKWhM2Day": 4.99,
  "coastal": false
 },
 {
  "iso": "TH-54",
  "solarCF": 0.158,
  "solarByMonth": [
   0.182,
   0.197,
   0.198,
   0.183,
   0.148,
   0.129,
   0.116,
   0.116,
   0.135,
   0.152,
   0.17,
   0.175
  ],
  "solarCFRange": [
   0.157,
   0.16
  ],
  "solarSamples": 6,
  "tiltDeg": 23,
  "windMS50": 3.08,
  "windByMonth": [
   2.79,
   2.84,
   3.21,
   3.36,
   3.19,
   3.69,
   3.65,
   3.38,
   2.61,
   2.5,
   2.7,
   3.06
  ],
  "ghiKWhM2Day": 4.87,
  "coastal": false
 },
 {
  "iso": "TH-55",
  "solarCF": 0.159,
  "solarByMonth": [
   0.183,
   0.197,
   0.197,
   0.184,
   0.15,
   0.129,
   0.116,
   0.116,
   0.138,
   0.157,
   0.172,
   0.175
  ],
  "solarCFRange": [
   0.157,
   0.161
  ],
  "solarSamples": 6,
  "tiltDeg": 24,
  "windMS50": 2.83,
  "windByMonth": [
   2.68,
   2.92,
   3.22,
   3.19,
   3.04,
   3.37,
   3.28,
   3.01,
   2.37,
   2.25,
   2.24,
   2.43
  ],
  "ghiKWhM2Day": 4.87,
  "coastal": false
 },
 {
  "iso": "TH-56",
  "solarCF": 0.163,
  "solarByMonth": [
   0.186,
   0.204,
   0.203,
   0.187,
   0.153,
   0.132,
   0.12,
   0.12,
   0.141,
   0.157,
   0.174,
   0.177
  ],
  "solarCFRange": [
   0.161,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 24,
  "windMS50": 3.11,
  "windByMonth": [
   2.65,
   2.96,
   3.44,
   3.55,
   3.46,
   3.92,
   3.81,
   3.48,
   2.67,
   2.39,
   2.41,
   2.55
  ],
  "ghiKWhM2Day": 4.82,
  "coastal": false
 },
 {
  "iso": "TH-57",
  "solarCF": 0.161,
  "solarByMonth": [
   0.183,
   0.204,
   0.203,
   0.184,
   0.153,
   0.132,
   0.12,
   0.122,
   0.141,
   0.154,
   0.171,
   0.174
  ],
  "solarCFRange": [
   0.16,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 24,
  "windMS50": 2.74,
  "windByMonth": [
   2.33,
   2.54,
   2.89,
   3.11,
   3.17,
   3.43,
   3.22,
   2.89,
   2.42,
   2.3,
   2.34,
   2.25
  ],
  "ghiKWhM2Day": 4.9,
  "coastal": false
 },
 {
  "iso": "TH-58",
  "solarCF": 0.157,
  "solarByMonth": [
   0.192,
   0.211,
   0.208,
   0.186,
   0.144,
   0.113,
   0.099,
   0.101,
   0.129,
   0.153,
   0.175,
   0.181
  ],
  "solarCFRange": [
   0.149,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 24,
  "windMS50": 2.4,
  "windByMonth": [
   2.08,
   2.3,
   2.62,
   2.59,
   2.51,
   2.88,
   2.83,
   2.6,
   2.14,
   2.09,
   2.05,
   2.08
  ],
  "ghiKWhM2Day": 4.8,
  "coastal": false
 },
 {
  "iso": "TH-60",
  "solarCF": 0.163,
  "solarByMonth": [
   0.187,
   0.195,
   0.192,
   0.181,
   0.155,
   0.141,
   0.129,
   0.129,
   0.142,
   0.152,
   0.172,
   0.18
  ],
  "solarCFRange": [
   0.155,
   0.166
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 3.63,
  "windByMonth": [
   3.44,
   3.54,
   3.68,
   3.68,
   3.57,
   4.01,
   4.04,
   3.86,
   3.1,
   3.13,
   3.61,
   3.9
  ],
  "ghiKWhM2Day": 5.21,
  "coastal": false
 },
 {
  "iso": "TH-61",
  "solarCF": 0.156,
  "solarByMonth": [
   0.183,
   0.191,
   0.19,
   0.176,
   0.148,
   0.13,
   0.117,
   0.119,
   0.133,
   0.145,
   0.167,
   0.176
  ],
  "solarCFRange": [
   0.155,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 20,
  "windMS50": 2.92,
  "windByMonth": [
   2.44,
   2.63,
   2.79,
   2.66,
   2.86,
   3.44,
   3.7,
   3.7,
   2.76,
   2.5,
   2.71,
   2.79
  ],
  "ghiKWhM2Day": 5,
  "coastal": false
 },
 {
  "iso": "TH-62",
  "solarCF": 0.156,
  "solarByMonth": [
   0.185,
   0.195,
   0.191,
   0.176,
   0.145,
   0.127,
   0.114,
   0.116,
   0.135,
   0.149,
   0.17,
   0.177
  ],
  "solarCFRange": [
   0.153,
   0.159
  ],
  "solarSamples": 6,
  "tiltDeg": 22,
  "windMS50": 3.4,
  "windByMonth": [
   2.96,
   3.51,
   3.71,
   3.38,
   3.42,
   3.97,
   4.23,
   4.16,
   3.25,
   2.57,
   2.66,
   2.94
  ],
  "ghiKWhM2Day": 5.02,
  "coastal": false
 },
 {
  "iso": "TH-63",
  "solarCF": 0.151,
  "solarByMonth": [
   0.193,
   0.203,
   0.197,
   0.175,
   0.131,
   0.101,
   0.086,
   0.09,
   0.118,
   0.154,
   0.179,
   0.186
  ],
  "solarCFRange": [
   0.141,
   0.154
  ],
  "solarSamples": 6,
  "tiltDeg": 24,
  "windMS50": 2.79,
  "windByMonth": [
   2.24,
   2.38,
   2.52,
   2.34,
   2.69,
   3.64,
   3.9,
   3.83,
   2.66,
   2.27,
   2.43,
   2.54
  ],
  "ghiKWhM2Day": 4.74,
  "coastal": false
 },
 {
  "iso": "TH-64",
  "solarCF": 0.159,
  "solarByMonth": [
   0.183,
   0.198,
   0.197,
   0.182,
   0.148,
   0.128,
   0.116,
   0.118,
   0.139,
   0.153,
   0.172,
   0.177
  ],
  "solarCFRange": [
   0.158,
   0.161
  ],
  "solarSamples": 6,
  "tiltDeg": 22,
  "windMS50": 3.19,
  "windByMonth": [
   2.86,
   2.84,
   3.23,
   3.48,
   3.33,
   3.86,
   3.87,
   3.62,
   2.75,
   2.46,
   2.73,
   3.22
  ],
  "ghiKWhM2Day": 5.05,
  "coastal": false
 },
 {
  "iso": "TH-65",
  "solarCF": 0.162,
  "solarByMonth": [
   0.186,
   0.197,
   0.198,
   0.186,
   0.154,
   0.133,
   0.121,
   0.12,
   0.138,
   0.154,
   0.176,
   0.181
  ],
  "solarCFRange": [
   0.161,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 22,
  "windMS50": 3.72,
  "windByMonth": [
   3.98,
   3.56,
   3.58,
   3.6,
   3.39,
   3.89,
   3.95,
   3.74,
   2.93,
   3.43,
   4,
   4.53
  ],
  "ghiKWhM2Day": 5.13,
  "coastal": false
 },
 {
  "iso": "TH-66",
  "solarCF": 0.161,
  "solarByMonth": [
   0.185,
   0.194,
   0.193,
   0.182,
   0.154,
   0.138,
   0.126,
   0.125,
   0.14,
   0.15,
   0.171,
   0.177
  ],
  "solarCFRange": [
   0.16,
   0.162
  ],
  "solarSamples": 6,
  "tiltDeg": 21,
  "windMS50": 3.97,
  "windByMonth": [
   4.28,
   4.03,
   3.99,
   3.87,
   3.68,
   4.14,
   4.11,
   3.91,
   3.12,
   3.54,
   4.19,
   4.75
  ],
  "ghiKWhM2Day": 5.13,
  "coastal": false
 },
 {
  "iso": "TH-67",
  "solarCF": 0.162,
  "solarByMonth": [
   0.188,
   0.196,
   0.194,
   0.182,
   0.153,
   0.135,
   0.123,
   0.123,
   0.137,
   0.154,
   0.178,
   0.186
  ],
  "solarCFRange": [
   0.16,
   0.168
  ],
  "solarSamples": 6,
  "tiltDeg": 21,
  "windMS50": 4.01,
  "windByMonth": [
   4.23,
   3.77,
   3.71,
   3.41,
   3.45,
   4.21,
   4.43,
   4.26,
   3.24,
   3.99,
   4.52,
   4.84
  ],
  "ghiKWhM2Day": 4.9,
  "coastal": false
 },
 {
  "iso": "TH-70",
  "solarCF": 0.156,
  "solarByMonth": [
   0.185,
   0.19,
   0.188,
   0.175,
   0.149,
   0.13,
   0.119,
   0.125,
   0.132,
   0.142,
   0.165,
   0.177
  ],
  "solarCFRange": [
   0.154,
   0.161
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 3.69,
  "windByMonth": [
   3.16,
   3.2,
   3.08,
   2.92,
   3.56,
   4.54,
   5.01,
   5.09,
   3.79,
   3.04,
   3.34,
   3.5
  ],
  "ghiKWhM2Day": 4.9,
  "coastal": false
 },
 {
  "iso": "TH-71",
  "solarCF": 0.15,
  "solarByMonth": [
   0.186,
   0.19,
   0.189,
   0.173,
   0.138,
   0.114,
   0.1,
   0.104,
   0.121,
   0.143,
   0.168,
   0.181
  ],
  "solarCFRange": [
   0.144,
   0.16
  ],
  "solarSamples": 6,
  "tiltDeg": 22,
  "windMS50": 2.84,
  "windByMonth": [
   2.67,
   2.25,
   2.17,
   2.08,
   2.57,
   3.35,
   3.69,
   3.77,
   2.83,
   2.56,
   2.96,
   3.16
  ],
  "ghiKWhM2Day": 5.06,
  "coastal": false
 },
 {
  "iso": "TH-72",
  "solarCF": 0.162,
  "solarByMonth": [
   0.186,
   0.192,
   0.192,
   0.182,
   0.155,
   0.139,
   0.127,
   0.13,
   0.139,
   0.15,
   0.169,
   0.178
  ],
  "solarCFRange": [
   0.16,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 4.35,
  "windByMonth": [
   3.99,
   3.84,
   4.04,
   3.99,
   4.13,
   4.89,
   5.19,
   5.16,
   3.98,
   3.7,
   4.45,
   4.77
  ],
  "ghiKWhM2Day": 5.06,
  "coastal": false
 },
 {
  "iso": "TH-73",
  "solarCF": 0.162,
  "solarByMonth": [
   0.182,
   0.19,
   0.192,
   0.182,
   0.157,
   0.142,
   0.131,
   0.135,
   0.141,
   0.149,
   0.166,
   0.174
  ],
  "solarCFRange": [
   0.161,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 18,
  "windMS50": 4.24,
  "windByMonth": [
   3.94,
   4.05,
   4.2,
   4.05,
   3.98,
   4.58,
   4.85,
   4.92,
   3.92,
   3.53,
   4.24,
   4.55
  ],
  "ghiKWhM2Day": 5.23,
  "coastal": false
 },
 {
  "iso": "TH-74",
  "solarCF": 0.166,
  "solarByMonth": [
   0.185,
   0.196,
   0.198,
   0.187,
   0.161,
   0.146,
   0.136,
   0.141,
   0.145,
   0.151,
   0.169,
   0.178
  ],
  "solarCFRange": [
   0.164,
   0.167
  ],
  "solarSamples": 3,
  "tiltDeg": 17,
  "windMS50": 4.21,
  "windByMonth": [
   4,
   4.36,
   4.49,
   4.27,
   3.96,
   4.43,
   4.69,
   4.72,
   3.8,
   3.41,
   4.08,
   4.4
  ],
  "ghiKWhM2Day": 5.23,
  "coastal": true
 },
 {
  "iso": "TH-75",
  "solarCF": 0.158,
  "solarByMonth": [
   0.185,
   0.192,
   0.191,
   0.179,
   0.15,
   0.133,
   0.122,
   0.128,
   0.134,
   0.143,
   0.165,
   0.179
  ],
  "solarCFRange": [
   0.158,
   0.16
  ],
  "solarSamples": 3,
  "tiltDeg": 18,
  "windMS50": 4.21,
  "windByMonth": [
   4,
   4.36,
   4.49,
   4.27,
   3.96,
   4.43,
   4.69,
   4.72,
   3.8,
   3.41,
   4.08,
   4.4
  ],
  "ghiKWhM2Day": 4.9,
  "coastal": true
 },
 {
  "iso": "TH-76",
  "solarCF": 0.15,
  "solarByMonth": [
   0.183,
   0.189,
   0.186,
   0.171,
   0.137,
   0.116,
   0.104,
   0.11,
   0.117,
   0.136,
   0.168,
   0.181
  ],
  "solarCFRange": [
   0.145,
   0.161
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 3.27,
  "windByMonth": [
   2.81,
   2.67,
   2.52,
   2.37,
   3.15,
   4.12,
   4.54,
   4.61,
   3.44,
   2.69,
   3.06,
   3.23
  ],
  "ghiKWhM2Day": 4.77,
  "coastal": true
 },
 {
  "iso": "TH-77",
  "solarCF": 0.155,
  "solarByMonth": [
   0.185,
   0.192,
   0.188,
   0.175,
   0.144,
   0.125,
   0.116,
   0.123,
   0.126,
   0.137,
   0.165,
   0.181
  ],
  "solarCFRange": [
   0.15,
   0.162
  ],
  "solarSamples": 6,
  "tiltDeg": 19,
  "windMS50": 2.94,
  "windByMonth": [
   2.69,
   2.35,
   2.19,
   2.07,
   2.77,
   3.51,
   3.79,
   3.92,
   3.21,
   2.59,
   2.99,
   3.19
  ],
  "ghiKWhM2Day": 4.82,
  "coastal": true
 },
 {
  "iso": "TH-80",
  "solarCF": 0.153,
  "solarByMonth": [
   0.156,
   0.184,
   0.184,
   0.171,
   0.152,
   0.146,
   0.147,
   0.153,
   0.149,
   0.135,
   0.129,
   0.134
  ],
  "solarCFRange": [
   0.153,
   0.154
  ],
  "solarSamples": 6,
  "tiltDeg": 9,
  "windMS50": 4.09,
  "windByMonth": [
   4.87,
   4.49,
   3.8,
   3.17,
   3.31,
   3.94,
   4.15,
   4.3,
   3.92,
   3.61,
   4.36,
   5.12
  ],
  "ghiKWhM2Day": 4.79,
  "coastal": true
 },
 {
  "iso": "TH-81",
  "solarCF": 0.16,
  "solarByMonth": [
   0.172,
   0.195,
   0.19,
   0.175,
   0.151,
   0.144,
   0.145,
   0.153,
   0.148,
   0.143,
   0.145,
   0.153
  ],
  "solarCFRange": [
   0.153,
   0.163
  ],
  "solarSamples": 6,
  "tiltDeg": 9,
  "windMS50": 3.23,
  "windByMonth": [
   3.33,
   3.15,
   2.73,
   2.49,
   3.09,
   3.57,
   3.69,
   3.84,
   3.57,
   3.03,
   2.9,
   3.39
  ],
  "ghiKWhM2Day": 4.79,
  "coastal": true
 },
 {
  "iso": "TH-82",
  "solarCF": 0.161,
  "solarByMonth": [
   0.176,
   0.196,
   0.191,
   0.177,
   0.151,
   0.143,
   0.144,
   0.152,
   0.146,
   0.145,
   0.152,
   0.162
  ],
  "solarCFRange": [
   0.153,
   0.168
  ],
  "solarSamples": 5,
  "tiltDeg": 9,
  "windMS50": 2.54,
  "windByMonth": [
   2.67,
   2.55,
   2.21,
   1.95,
   2.37,
   2.73,
   2.8,
   2.91,
   2.73,
   2.34,
   2.42,
   2.76
  ],
  "ghiKWhM2Day": 5.02,
  "coastal": true
 },
 {
  "iso": "TH-83",
  "solarCF": 0.175,
  "solarByMonth": [
   0.192,
   0.213,
   0.206,
   0.188,
   0.162,
   0.156,
   0.157,
   0.167,
   0.163,
   0.16,
   0.163,
   0.173
  ],
  "solarCFRange": [
   0.175,
   0.176
  ],
  "solarSamples": 3,
  "tiltDeg": 10,
  "windMS50": 4.06,
  "windByMonth": [
   4.12,
   3.76,
   3.39,
   2.99,
   3.9,
   4.67,
   4.84,
   5.02,
   4.55,
   3.76,
   3.48,
   4.2
  ],
  "ghiKWhM2Day": 5.3,
  "coastal": true
 },
 {
  "iso": "TH-84",
  "solarCF": 0.154,
  "solarByMonth": [
   0.166,
   0.189,
   0.185,
   0.171,
   0.147,
   0.139,
   0.138,
   0.145,
   0.139,
   0.136,
   0.142,
   0.152
  ],
  "solarCFRange": [
   0.148,
   0.174
  ],
  "solarSamples": 6,
  "tiltDeg": 11,
  "windMS50": 3.92,
  "windByMonth": [
   4.44,
   3.94,
   3.39,
   3,
   3.39,
   4.04,
   4.17,
   4.31,
   3.9,
   3.48,
   4.19,
   4.8
  ],
  "ghiKWhM2Day": 4.91,
  "coastal": true
 },
 {
  "iso": "TH-85",
  "solarCF": 0.159,
  "solarByMonth": [
   0.177,
   0.196,
   0.191,
   0.177,
   0.15,
   0.138,
   0.136,
   0.146,
   0.139,
   0.142,
   0.152,
   0.163
  ],
  "solarCFRange": [
   0.147,
   0.164
  ],
  "solarSamples": 5,
  "tiltDeg": 13,
  "windMS50": 3.2,
  "windByMonth": [
   3.35,
   3,
   2.58,
   2.28,
   2.92,
   3.59,
   3.71,
   3.83,
   3.4,
   2.87,
   3.25,
   3.58
  ],
  "ghiKWhM2Day": 4.84,
  "coastal": true
 },
 {
  "iso": "TH-86",
  "solarCF": 0.16,
  "solarByMonth": [
   0.18,
   0.196,
   0.194,
   0.179,
   0.153,
   0.139,
   0.136,
   0.146,
   0.14,
   0.141,
   0.153,
   0.166
  ],
  "solarCFRange": [
   0.157,
   0.164
  ],
  "solarSamples": 6,
  "tiltDeg": 14,
  "windMS50": 4.23,
  "windByMonth": [
   4.24,
   3.79,
   3.31,
   2.94,
   3.96,
   5,
   5.21,
   5.37,
   4.65,
   3.7,
   4.11,
   4.5
  ],
  "ghiKWhM2Day": 4.93,
  "coastal": true
 },
 {
  "iso": "TH-90",
  "solarCF": 0.162,
  "solarByMonth": [
   0.169,
   0.193,
   0.19,
   0.177,
   0.159,
   0.156,
   0.157,
   0.165,
   0.157,
   0.148,
   0.138,
   0.142
  ],
  "solarCFRange": [
   0.161,
   0.166
  ],
  "solarSamples": 6,
  "tiltDeg": 5,
  "windMS50": 4.43,
  "windByMonth": [
   6.04,
   5.81,
   4.87,
   3.87,
   3.18,
   3.51,
   3.74,
   3.96,
   3.87,
   3.78,
   4.7,
   5.96
  ],
  "ghiKWhM2Day": 5.02,
  "coastal": true
 },
 {
  "iso": "TH-91",
  "solarCF": 0.167,
  "solarByMonth": [
   0.179,
   0.202,
   0.195,
   0.179,
   0.158,
   0.155,
   0.156,
   0.165,
   0.159,
   0.153,
   0.148,
   0.154
  ],
  "solarCFRange": [
   0.158,
   0.174
  ],
  "solarSamples": 6,
  "tiltDeg": 8,
  "windMS50": 3.49,
  "windByMonth": [
   4.56,
   4.41,
   3.54,
   2.75,
   2.71,
   3.07,
   3.2,
   3.4,
   3.27,
   3.06,
   3.52,
   4.45
  ],
  "ghiKWhM2Day": 5.13,
  "coastal": true
 },
 {
  "iso": "TH-92",
  "solarCF": 0.161,
  "solarByMonth": [
   0.172,
   0.197,
   0.192,
   0.175,
   0.154,
   0.149,
   0.151,
   0.158,
   0.153,
   0.144,
   0.142,
   0.148
  ],
  "solarCFRange": [
   0.155,
   0.17
  ],
  "solarSamples": 6,
  "tiltDeg": 8,
  "windMS50": 3.11,
  "windByMonth": [
   3.48,
   3.41,
   2.81,
   2.38,
   2.79,
   3.18,
   3.3,
   3.5,
   3.29,
   2.89,
   2.88,
   3.42
  ],
  "ghiKWhM2Day": 5.01,
  "coastal": true
 },
 {
  "iso": "TH-93",
  "solarCF": 0.158,
  "solarByMonth": [
   0.166,
   0.193,
   0.19,
   0.174,
   0.154,
   0.149,
   0.15,
   0.157,
   0.152,
   0.14,
   0.133,
   0.138
  ],
  "solarCFRange": [
   0.154,
   0.161
  ],
  "solarSamples": 6,
  "tiltDeg": 7,
  "windMS50": 3.64,
  "windByMonth": [
   4.68,
   4.49,
   3.71,
   2.95,
   2.83,
   3.23,
   3.35,
   3.55,
   3.37,
   3.15,
   3.79,
   4.65
  ],
  "ghiKWhM2Day": 5.01,
  "coastal": false
 },
 {
  "iso": "TH-94",
  "solarCF": 0.158,
  "solarByMonth": [
   0.153,
   0.184,
   0.188,
   0.178,
   0.162,
   0.159,
   0.159,
   0.166,
   0.159,
   0.144,
   0.126,
   0.124
  ],
  "solarCFRange": [
   0.156,
   0.166
  ],
  "solarSamples": 6,
  "tiltDeg": 6,
  "windMS50": 2.55,
  "windByMonth": [
   3.29,
   3.19,
   2.79,
   2.35,
   1.95,
   2.02,
   2.15,
   2.28,
   2.33,
   2.34,
   2.67,
   3.25
  ],
  "ghiKWhM2Day": 4.96,
  "coastal": true
 },
 {
  "iso": "TH-95",
  "solarCF": 0.156,
  "solarByMonth": [
   0.155,
   0.183,
   0.183,
   0.171,
   0.155,
   0.156,
   0.155,
   0.162,
   0.155,
   0.144,
   0.129,
   0.129
  ],
  "solarCFRange": [
   0.155,
   0.157
  ],
  "solarSamples": 6,
  "tiltDeg": 6,
  "windMS50": 2.36,
  "windByMonth": [
   3.03,
   2.89,
   2.43,
   2,
   1.81,
   1.96,
   2.07,
   2.2,
   2.23,
   2.26,
   2.46,
   3
  ],
  "ghiKWhM2Day": 4.96,
  "coastal": false
 },
 {
  "iso": "TH-96",
  "solarCF": 0.156,
  "solarByMonth": [
   0.146,
   0.177,
   0.184,
   0.176,
   0.159,
   0.156,
   0.156,
   0.166,
   0.161,
   0.148,
   0.127,
   0.12
  ],
  "solarCFRange": [
   0.154,
   0.16
  ],
  "solarSamples": 6,
  "tiltDeg": 6,
  "windMS50": 2.65,
  "windByMonth": [
   3.48,
   3.26,
   2.85,
   2.52,
   2.11,
   2.08,
   2.11,
   2.23,
   2.31,
   2.51,
   2.86,
   3.48
  ],
  "ghiKWhM2Day": 4.96,
  "coastal": true
 }
];
