import { describe, it, expect } from "vitest";
import { PROVINCE_RESOURCE } from "./attributes";
import { PROVINCES } from "./provinces";
import { CF_BY_SEASON, MONTH_SEASON } from "@/data/constants";

/**
 * attributes.ts is fetched from two public APIs and regenerated by hand, which
 * is exactly the kind of file that rots without anyone noticing: an endpoint
 * changes its response shape, the parse yields undefined, `+(undefined)` is
 * NaN, and the map shades every province the same colour without throwing.
 *
 * So these tests are less about arithmetic than about the data still being
 * data. They also pin down the two things that were established by measurement
 * rather than assumption — the coastal list and the mildness of the solar
 * season — so that a refetch which quietly disagrees has to argue with a
 * failing test rather than slip through.
 */

const byIso = new Map(PROVINCE_RESOURCE.map((r) => [r.iso, r]));

describe("every province has resource data", () => {
  it("matches the province list exactly", () => {
    expect(PROVINCE_RESOURCE).toHaveLength(PROVINCES.length);
    expect(new Set(PROVINCE_RESOURCE.map((r) => r.iso))).toEqual(
      new Set(PROVINCES.map((p) => p.iso)),
    );
  });

  it("has no missing or nonsensical figures", () => {
    for (const r of PROVINCE_RESOURCE) {
      // Thailand's solar resource is genuinely uniform; anything outside this
      // is a parse failure, not a province.
      expect(r.solarCF, r.iso).toBeGreaterThan(0.1);
      expect(r.solarCF, r.iso).toBeLessThan(0.25);
      expect(r.windMS50, r.iso).toBeGreaterThan(0.5);
      expect(r.windMS50, r.iso).toBeLessThan(15);
      expect(r.ghiKWhM2Day, r.iso).toBeGreaterThan(3);
      expect(r.solarByMonth, r.iso).toHaveLength(12);
      expect(r.windByMonth, r.iso).toHaveLength(12);
      for (const v of r.solarByMonth ?? []) expect(Number.isFinite(v)).toBe(true);
      for (const v of r.windByMonth) expect(Number.isFinite(v)).toBe(true);
    }
  });

  it("keeps the monthly figures consistent with the annual one", () => {
    for (const r of PROVINCE_RESOURCE) {
      const mean =
        (r.solarByMonth ?? []).reduce((s, v) => s + v, 0) / 12;
      // Month lengths differ, so these can't be identical — but a 5% gap
      // would mean the two came from different requests.
      expect(Math.abs(mean - r.solarCF) / r.solarCF, r.iso).toBeLessThan(0.05);
    }
  });
});

describe("the coastal flag, which is derived rather than typed in", () => {
  const coastal = PROVINCE_RESOURCE.filter((r) => r.coastal).map((r) => r.iso);

  it("finds the 23 provinces Thailand actually has on the sea", () => {
    expect(coastal).toHaveLength(23);
  });

  it("includes the awkward cases and excludes their neighbours", () => {
    // Bangkok reaches the Gulf through Bang Khun Thian by a few kilometres of
    // mangrove, and it would be easy for a threshold to miss it. Nonthaburi
    // and Pathum Thani sit right beside Bangkok on the same river and must
    // not come along with it.
    expect(byIso.get("TH-10")?.coastal, "Bangkok").toBe(true);
    expect(byIso.get("TH-12")?.coastal, "Nonthaburi").toBe(false);
    expect(byIso.get("TH-13")?.coastal, "Pathum Thani").toBe(false);
    // Phang-nga and Krabi are coastal; Ratchaburi, one province inland from
    // Phetchaburi's shoreline, is not.
    expect(byIso.get("TH-82")?.coastal, "Phang-nga").toBe(true);
    expect(byIso.get("TH-81")?.coastal, "Krabi").toBe(true);
    expect(byIso.get("TH-70")?.coastal, "Ratchaburi").toBe(false);
  });
});

describe("what the measurements say about the model's assumptions", () => {
  /** Average the monthly figures into the app's four seasons. */
  function bySeason(monthly: number[]) {
    const sum: Record<string, number> = {};
    const n: Record<string, number> = {};
    monthly.forEach((v, i) => {
      const s = MONTH_SEASON[i];
      sum[s] = (sum[s] ?? 0) + v;
      n[s] = (n[s] ?? 0) + 1;
    });
    return Object.fromEntries(
      Object.keys(sum).map((s) => [s, sum[s] / n[s]]),
    ) as Record<string, number>;
  }

  it("agrees with CF_BY_SEASON on the annual level of solar", () => {
    const pb = byIso.get("TH-76")!;
    const modelled =
      MONTH_SEASON.reduce((s, k) => s + CF_BY_SEASON[k].solar, 0) / 12;
    // Within 10%: the model's overall solar yield for Phetchaburi is sound.
    expect(Math.abs(modelled - pb.solarCF) / pb.solarCF).toBeLessThan(0.1);
  });

  it("is where the season table's solar figures come from", () => {
    // CF_BY_SEASON.solar is derived from these monthly numbers rather than
    // typed in, so this checks the fold: each season is the mean of the months
    // MONTH_SEASON assigns to it. A wrong fold — an off-by-one in the month
    // map, or averaging the wrong way — would still produce four plausible
    // numbers, which is exactly why it is worth pinning.
    const pb = byIso.get("TH-76")!;
    const real = bySeason(pb.solarByMonth!);
    for (const s of ["summer", "rainy", "winter", "monsoon"] as const) {
      expect(CF_BY_SEASON[s].solar, s).toBeCloseTo(real[s], 3);
    }
  });

  it("keeps the seasonal swing as mild as the satellites say it is", () => {
    // This table used to run summer 0.22 down to monsoon 0.05 — a 4.4x swing
    // against a measured 1.6x — which had the model generating 39% of the real
    // September and October output and sizing storage for a drought that does
    // not happen. Guarding the swing means a future refetch, or a hand edit,
    // cannot quietly reintroduce it.
    const solar = Object.values(CF_BY_SEASON).map((v) => v.solar);
    expect(Math.max(...solar) / Math.min(...solar)).toBeLessThan(2);
  });

  it("has no province collapsing the way the old table claimed", () => {
    // The old table's worst season kept 23% of its best. No province measured
    // comes near that: the deepest is Mae Hong Son, in the northwestern
    // mountains under the heaviest monsoon in the country, whose worst month
    // still keeps 48% of its best.
    //
    // The threshold is 0.4, which is neither of those numbers on purpose. Set
    // at Mae Hong Son's 0.477 this test would only restate the sample and
    // would break on any refetch; set at 0.23 it would pass even if the data
    // started agreeing with the assumption it exists to question.
    for (const r of PROVINCE_RESOURCE) {
      const m = r.solarByMonth!;
      expect(Math.min(...m) / Math.max(...m), r.iso).toBeGreaterThan(0.4);
    }
  });
});

describe("how much a single province-level number is hiding", () => {
  it("samples several amphoe per province, not one point", () => {
    for (const r of PROVINCE_RESOURCE) {
      expect(r.solarSamples, r.iso).toBeGreaterThanOrEqual(1);
      expect(r.solarCFRange[0], r.iso).toBeLessThanOrEqual(r.solarCF);
      expect(r.solarCFRange[1], r.iso).toBeGreaterThanOrEqual(r.solarCF);
    }
    // Only a handful of provinces have fewer than four amphoe; if this drops,
    // the sampling has quietly reverted to something like a single point.
    const wellSampled = PROVINCE_RESOURCE.filter((r) => r.solarSamples >= 4);
    expect(wellSampled.length).toBeGreaterThan(65);
  });

  it("finds a province's own spread rivals the whole country's", () => {
    /*
     * This is the reason the map tells readers not to rank provinces by
     * sunshine, and it is worth pinning because it is counterintuitive
     * enough that someone will later "fix" the caption.
     *
     * Nationwide the CF spans about 0.025. Surat Thani spans 0.026 across
     * its own amphoe; Phetchaburi 0.016. Sorting 77 provinces by a number
     * with that much internal variation is sorting noise.
     */
    const all = PROVINCE_RESOURCE.map((r) => r.solarCF);
    const national = Math.max(...all) - Math.min(...all);
    const widest = Math.max(
      ...PROVINCE_RESOURCE.map((r) => r.solarCFRange[1] - r.solarCFRange[0]),
    );
    expect(widest).toBeGreaterThan(national * 0.8);
  });

  it("still separates the sunny northeast from the wet west", () => {
    // The ranking is noisy, not meaningless: the plateau provinces really do
    // beat the western mountains, and that survives the amphoe averaging.
    const cf = (iso: string) => byIso.get(iso)!.solarCF;
    for (const isaan of ["TH-45", "TH-44", "TH-46"]) {
      for (const west of ["TH-76", "TH-71", "TH-63"]) {
        expect(cf(isaan), `${isaan} vs ${west}`).toBeGreaterThan(cf(west));
      }
    }
  });
});
