import { describe, it, expect } from "vitest";
import { PROVINCE_RESOURCE } from "./attributes";
import { PROVINCES } from "./provinces";
import { CF_BY_SEASON, MONTH_SEASON } from "@/data/constants";

/**
 * attributes.ts is fetched from two public APIs and regenerated by hand, which
 * is exactly the kind of file that rots without anyone noticing: an endpoint
 * changes its response shape, the parse yields undefined, `+(undefined)` is
 * NaN, and the map shades every province the same colour without throwing.
 *
 * So these tests are less about arithmetic than about the data still being
 * data. They also pin down the two things that were established by measurement
 * rather than assumption — the coastal list and the mildness of the solar
 * season — so that a refetch which quietly disagrees has to argue with a
 * failing test rather than slip through.
 */

const byIso = new Map(PROVINCE_RESOURCE.map((r) => [r.iso, r]));

describe("every province has resource data", () => {
  it("matches the province list exactly", () => {
    expect(PROVINCE_RESOURCE).toHaveLength(PROVINCES.length);
    expect(new Set(PROVINCE_RESOURCE.map((r) => r.iso))).toEqual(
      new Set(PROVINCES.map((p) => p.iso)),
    );
  });

  it("has no missing or nonsensical figures", () => {
    for (const r of PROVINCE_RESOURCE) {
      // Thailand's solar resource is genuinely uniform; anything outside this
      // is a parse failure, not a province.
      expect(r.solarCF, r.iso).toBeGreaterThan(0.1);
      expect(r.solarCF, r.iso).toBeLessThan(0.25);
      expect(r.windMS50, r.iso).toBeGreaterThan(0.5);
      expect(r.windMS50, r.iso).toBeLessThan(15);
      expect(r.ghiKWhM2Day, r.iso).toBeGreaterThan(3);
      expect(r.solarByMonth, r.iso).toHaveLength(12);
      expect(r.windByMonth, r.iso).toHaveLength(12);
      for (const v of r.solarByMonth ?? []) expect(Number.isFinite(v)).toBe(true);
      for (const v of r.windByMonth) expect(Number.isFinite(v)).toBe(true);
    }
  });

  it("keeps the monthly figures consistent with the annual one", () => {
    for (const r of PROVINCE_RESOURCE) {
      const mean =
        (r.solarByMonth ?? []).reduce((s, v) => s + v, 0) / 12;
      // Month lengths differ, so these can't be identical — but a 5% gap
      // would mean the two came from different requests.
      expect(Math.abs(mean - r.solarCF) / r.solarCF, r.iso).toBeLessThan(0.05);
    }
  });
});

describe("the coastal flag, which is derived rather than typed in", () => {
  const coastal = PROVINCE_RESOURCE.filter((r) => r.coastal).map((r) => r.iso);

  it("finds the 23 provinces Thailand actually has on the sea", () => {
    expect(coastal).toHaveLength(23);
  });

  it("includes the awkward cases and excludes their neighbours", () => {
    // Bangkok reaches the Gulf through Bang Khun Thian by a few kilometres of
    // mangrove, and it would be easy for a threshold to miss it. Nonthaburi
    // and Pathum Thani sit right beside Bangkok on the same river and must
    // not come along with it.
    expect(byIso.get("TH-10")?.coastal, "Bangkok").toBe(true);
    expect(byIso.get("TH-12")?.coastal, "Nonthaburi").toBe(false);
    expect(byIso.get("TH-13")?.coastal, "Pathum Thani").toBe(false);
    // Phang-nga and Krabi are coastal; Ratchaburi, one province inland from
    // Phetchaburi's shoreline, is not.
    expect(byIso.get("TH-82")?.coastal, "Phang-nga").toBe(true);
    expect(byIso.get("TH-81")?.coastal, "Krabi").toBe(true);
    expect(byIso.get("TH-70")?.coastal, "Ratchaburi").toBe(false);
  });
});

describe("what the measurements say about the model's assumptions", () => {
  /** Average the monthly figures into the app's four seasons. */
  function bySeason(monthly: number[]) {
    const sum: Record<string, number> = {};
    const n: Record<string, number> = {};
    monthly.forEach((v, i) => {
      const s = MONTH_SEASON[i];
      sum[s] = (sum[s] ?? 0) + v;
      n[s] = (n[s] ?? 0) + 1;
    });
    return Object.fromEntries(
      Object.keys(sum).map((s) => [s, sum[s] / n[s]]),
    ) as Record<string, number>;
  }

  it("agrees with CF_BY_SEASON on the annual level of solar", () => {
    const pb = byIso.get("TH-76")!;
    const modelled =
      MONTH_SEASON.reduce((s, k) => s + CF_BY_SEASON[k].solar, 0) / 12;
    // Within 10%: the model's overall solar yield for Phetchaburi is sound.
    expect(Math.abs(modelled - pb.solarCF) / pb.solarCF).toBeLessThan(0.1);
  });

  it("disagrees with it on the shape, and that disagreement is the finding", () => {
    const pb = byIso.get("TH-76")!;
    const real = bySeason(pb.solarByMonth!);
    const swing = (o: Record<string, number>) =>
      Math.max(...Object.values(o)) / Math.min(...Object.values(o));

    const modelSwing = swing(
      Object.fromEntries(
        Object.entries(CF_BY_SEASON).map(([k, v]) => [k, v.solar]),
      ),
    );
    // The model swings 4.4x from summer to monsoon. Two independent
    // satellite products put the real swing near 1.5x, agreeing with each
    // other at r = 0.955. Asserting both sides keeps this test honest: it
    // fails if the data starts claiming a swing it shouldn't, and it fails
    // if someone edits CF_BY_SEASON without revisiting this.
    expect(swing(real)).toBeLessThan(2);
    expect(modelSwing).toBeGreaterThan(3);
  });

  it("does not let the monsoon collapse the way the model assumes", () => {
    // CF_BY_SEASON puts monsoon solar at 0.05 against summer's 0.22 — the
    // worst season keeping 23% of the best. No province measured comes close
    // to collapsing that far: the deepest is Mae Hong Son, in the northwestern
    // mountains under the heaviest monsoon in the country, whose worst month
    // still keeps 48% of its best.
    //
    // The threshold is 0.4, which is neither of those numbers on purpose. Set
    // at Mae Hong Son's 0.477 this test would only be restating the sample and
    // would break on any refetch; set at the model's 0.23 it would pass even
    // if the data started agreeing with the assumption it exists to question.
    const modelRatio = CF_BY_SEASON.monsoon.solar / CF_BY_SEASON.summer.solar;
    expect(modelRatio).toBeLessThan(0.4);
    for (const r of PROVINCE_RESOURCE) {
      const m = r.solarByMonth!;
      expect(Math.min(...m) / Math.max(...m), r.iso).toBeGreaterThan(0.4);
    }
  });
});
