// GENERATED by scripts/fetch-province-electricity.mjs — do not edit.
//
// Electricity actually consumed, per province, from the Ministry of Energy's
// GD Catalog (dataset_41_07). BE 2566 (2023) is the headline year;
// `series` carries BE 2561-2566 so a trend is visible.
//
// All 77 provinces, measured — nothing here is estimated. That is worth
// stating because the obvious source is worse: EPPO's per-province CSV covers
// 66 provinces for 2016-2017 and omits Bangkok, Chiang Mai and Khon Kaen,
// which are a third of national demand. Filling those from population does
// not work — consumption against population fits at R² = 0.33, and R² = 0.19
// for industry, because factories are not sited where people live.
//
// The groups below are tariff classes, not economic sectors. "business" is
// small through large-scale commercial supply, which is defined by connected
// load rather than by what the customer does, so it holds both a shopping mall
// and a factory. Splitting it into commercial and industrial would be an
// invention.
//
// National total for BE 2566: 202.9 TWh.

export interface ProvinceElectricity {
  iso: string;
  /** GWh consumed in BE 2566. */
  gwhPerYear: number;
  /** The same figure per day, which is the unit the simulator works in. */
  gwhPerDay: number;
  /** kWh per resident per year — null where population is unknown. */
  kwhPerPerson: number | null;
  /** GWh by tariff class. EV charging is separate: it is the only real
   *  starting value the EV adoption curve has. */
  byClass: {
    residential: number;
    business: number;
    government: number;
    agriculture: number;
    ev: number;
    other: number;
  };
  /** Annual GWh, BE 2561 through 2566, oldest first. */
  series: number[];
}

export const PROVINCE_ELECTRICITY: ProvinceElectricity[] = [
 {
  "iso": "TH-10",
  "gwhPerYear": 37660.3,
  "gwhPerDay": 103.179,
  "kwhPerPerson": null,
  "byClass": {
   "residential": 11938.1,
   "business": 24898.4,
   "government": 479.5,
   "agriculture": 0,
   "ev": 61.5,
   "other": 282.8
  },
  "series": [
   36160.4,
   37548.1,
   35207.5,
   33843.7,
   35287.5,
   37660.3
  ]
 },
 {
  "iso": "TH-11",
  "gwhPerYear": 10365,
  "gwhPerDay": 28.397,
  "kwhPerPerson": 7669,
  "byClass": {
   "residential": 2095.8,
   "business": 7899.4,
   "government": 84.3,
   "agriculture": 0,
   "ev": 7.8,
   "other": 277.7
  },
  "series": [
   10383.4,
   10225.6,
   9662.5,
   10157.5,
   10449.3,
   10365
  ]
 },
 {
  "iso": "TH-12",
  "gwhPerYear": 5865.5,
  "gwhPerDay": 16.07,
  "kwhPerPerson": 4526,
  "byClass": {
   "residential": 2584,
   "business": 3125.1,
   "government": 91.4,
   "agriculture": 0,
   "ev": 10,
   "other": 55.1
  },
  "series": [
   5056.4,
   5530.6,
   6219,
   5558.6,
   5747.5,
   5865.5
  ]
 },
 {
  "iso": "TH-13",
  "gwhPerYear": 8160.2,
  "gwhPerDay": 22.357,
  "kwhPerPerson": 6937,
  "byClass": {
   "residential": 2120.5,
   "business": 5819.8,
   "government": 128.2,
   "agriculture": 0.2,
   "ev": 1.9,
   "other": 89.7
  },
  "series": [
   7462.4,
   7819.6,
   7715.7,
   7609.4,
   7898.6,
   8160.2
  ]
 },
 {
  "iso": "TH-14",
  "gwhPerYear": 5459.7,
  "gwhPerDay": 14.958,
  "kwhPerPerson": 6666,
  "byClass": {
   "residential": 906.6,
   "business": 4300.6,
   "government": 78.7,
   "agriculture": 5.3,
   "ev": 0.4,
   "other": 168.1
  },
  "series": [
   5576.5,
   5251.2,
   5175.6,
   5554.4,
   5856.6,
   5459.7
  ]
 },
 {
  "iso": "TH-15",
  "gwhPerYear": 638.9,
  "gwhPerDay": 1.75,
  "kwhPerPerson": 2310,
  "byClass": {
   "residential": 229.1,
   "business": 374.5,
   "government": 30.5,
   "agriculture": 0.4,
   "ev": 0,
   "other": 4.3
  },
  "series": [
   556.9,
   575.9,
   576.4,
   587.5,
   588.6,
   638.9
  ]
 },
 {
  "iso": "TH-16",
  "gwhPerYear": 2459.9,
  "gwhPerDay": 6.739,
  "kwhPerPerson": 3311,
  "byClass": {
   "residential": 566.8,
   "business": 1834.4,
   "government": 43.8,
   "agriculture": 4.1,
   "ev": 0.1,
   "other": 10.8
  },
  "series": [
   2308.8,
   2432.7,
   2424,
   2466.4,
   2457.2,
   2459.9
  ]
 },
 {
  "iso": "TH-17",
  "gwhPerYear": 652,
  "gwhPerDay": 1.786,
  "kwhPerPerson": 3167,
  "byClass": {
   "residential": 171.6,
   "business": 454.7,
   "government": 22.2,
   "agriculture": 0.2,
   "ev": 0.2,
   "other": 3.1
  },
  "series": [
   659.7,
   655.1,
   674.5,
   692.7,
   700.8,
   652
  ]
 },
 {
  "iso": "TH-18",
  "gwhPerYear": 668.5,
  "gwhPerDay": 1.832,
  "kwhPerPerson": 2073,
  "byClass": {
   "residential": 230.7,
   "business": 395,
   "government": 32,
   "agriculture": 6.7,
   "ev": 0,
   "other": 4.1
  },
  "series": [
   519.5,
   521.3,
   549.5,
   593.1,
   612.3,
   668.5
  ]
 },
 {
  "iso": "TH-19",
  "gwhPerYear": 5844.9,
  "gwhPerDay": 16.014,
  "kwhPerPerson": 9078,
  "byClass": {
   "residential": 682.8,
   "business": 3485.4,
   "government": 55.9,
   "agriculture": 10.9,
   "ev": 0.1,
   "other": 1609.8
  },
  "series": [
   755.1,
   5880.4,
   5754.1,
   5921.5,
   6282.6,
   5844.9
  ]
 },
 {
  "iso": "TH-20",
  "gwhPerYear": 14634.7,
  "gwhPerDay": 40.095,
  "kwhPerPerson": 9340,
  "byClass": {
   "residential": 2681.6,
   "business": 11673.2,
   "government": 135,
   "agriculture": 0,
   "ev": 1,
   "other": 143.9
  },
  "series": [
   12454,
   12951.9,
   12392.2,
   13301.3,
   13899.4,
   14634.7
  ]
 },
 {
  "iso": "TH-21",
  "gwhPerYear": 11008.5,
  "gwhPerDay": 30.16,
  "kwhPerPerson": 14846,
  "byClass": {
   "residential": 1220,
   "business": 9468.4,
   "government": 83.9,
   "agriculture": 39.6,
   "ev": 0,
   "other": 196.5
  },
  "series": [
   10505.7,
   10638.7,
   9937,
   10840,
   11032.6,
   11008.5
  ]
 },
 {
  "iso": "TH-22",
  "gwhPerYear": 1483.1,
  "gwhPerDay": 4.063,
  "kwhPerPerson": 2769,
  "byClass": {
   "residential": 681.6,
   "business": 742.5,
   "government": 45.1,
   "agriculture": 4.7,
   "ev": 0.1,
   "other": 9
  },
  "series": [
   1191.6,
   1304.9,
   1352.9,
   1345,
   1386.2,
   1483.1
  ]
 },
 {
  "iso": "TH-23",
  "gwhPerYear": 576.8,
  "gwhPerDay": 1.58,
  "kwhPerPerson": 2524,
  "byClass": {
   "residential": 206,
   "business": 347.6,
   "government": 18,
   "agriculture": 1.2,
   "ev": 0,
   "other": 3.9
  },
  "series": [
   566.2,
   579,
   591.2,
   561.9,
   559.9,
   576.8
  ]
 },
 {
  "iso": "TH-24",
  "gwhPerYear": 5471.7,
  "gwhPerDay": 14.991,
  "kwhPerPerson": 7592,
  "byClass": {
   "residential": 776.3,
   "business": 4594.6,
   "government": 58.6,
   "agriculture": 4.8,
   "ev": 0.2,
   "other": 37.1
  },
  "series": [
   5082.8,
   5183.4,
   4962.2,
   5309.7,
   5459.1,
   5471.7
  ]
 },
 {
  "iso": "TH-25",
  "gwhPerYear": 3549,
  "gwhPerDay": 9.723,
  "kwhPerPerson": 7189,
  "byClass": {
   "residential": 451.1,
   "business": 3036.4,
   "government": 45.7,
   "agriculture": 4.3,
   "ev": 0.2,
   "other": 11.4
  },
  "series": [
   2136.2,
   2174.4,
   2139,
   2593.6,
   3155.1,
   3549
  ]
 },
 {
  "iso": "TH-26",
  "gwhPerYear": 697.5,
  "gwhPerDay": 1.911,
  "kwhPerPerson": 2682,
  "byClass": {
   "residential": 238.4,
   "business": 428.2,
   "government": 25.3,
   "agriculture": 0.2,
   "ev": 0.1,
   "other": 5.3
  },
  "series": [
   564.6,
   596.5,
   625.7,
   636.7,
   656.4,
   697.5
  ]
 },
 {
  "iso": "TH-27",
  "gwhPerYear": 922.9,
  "gwhPerDay": 2.528,
  "kwhPerPerson": 1645,
  "byClass": {
   "residential": 334.1,
   "business": 541.9,
   "government": 40.1,
   "agriculture": 0.4,
   "ev": 0,
   "other": 6.3
  },
  "series": [
   6332.4,
   833.9,
   859.4,
   881.1,
   941.5,
   922.9
  ]
 },
 {
  "iso": "TH-30",
  "gwhPerYear": 6452,
  "gwhPerDay": 17.677,
  "kwhPerPerson": 2450,
  "byClass": {
   "residential": 1731.7,
   "business": 4536.4,
   "government": 120.1,
   "agriculture": 6.2,
   "ev": 1.1,
   "other": 56.4
  },
  "series": [
   6095.8,
   6173.1,
   6111.8,
   6345.3,
   6377.6,
   6452
  ]
 },
 {
  "iso": "TH-31",
  "gwhPerYear": 1459,
  "gwhPerDay": 3.997,
  "kwhPerPerson": 923,
  "byClass": {
   "residential": 665,
   "business": 712.6,
   "government": 66.7,
   "agriculture": 3.8,
   "ev": 0.1,
   "other": 10.7
  },
  "series": [
   1134.8,
   1204.6,
   1281,
   1354.9,
   1372.9,
   1459
  ]
 },
 {
  "iso": "TH-32",
  "gwhPerYear": 1089.4,
  "gwhPerDay": 2.985,
  "kwhPerPerson": 790,
  "byClass": {
   "residential": 535.8,
   "business": 491.5,
   "government": 48.3,
   "agriculture": 4.8,
   "ev": 0.1,
   "other": 8.9
  },
  "series": [
   876.5,
   930,
   992.2,
   1035.9,
   1042.5,
   1089.4
  ]
 },
 {
  "iso": "TH-33",
  "gwhPerYear": 1097.2,
  "gwhPerDay": 3.006,
  "kwhPerPerson": 752,
  "byClass": {
   "residential": 560.2,
   "business": 471.9,
   "government": 55.2,
   "agriculture": 2.9,
   "ev": 0.1,
   "other": 6.9
  },
  "series": [
   813.7,
   871.3,
   958.8,
   1016.2,
   1022.3,
   1097.2
  ]
 },
 {
  "iso": "TH-34",
  "gwhPerYear": 1863.7,
  "gwhPerDay": 5.106,
  "kwhPerPerson": 998,
  "byClass": {
   "residential": 840.6,
   "business": 919.2,
   "government": 77.1,
   "agriculture": 13.6,
   "ev": 0.4,
   "other": 12.7
  },
  "series": [
   1518.4,
   1617.2,
   1758.9,
   1840.1,
   1791.5,
   1863.7
  ]
 },
 {
  "iso": "TH-35",
  "gwhPerYear": 473.3,
  "gwhPerDay": 1.297,
  "kwhPerPerson": 885,
  "byClass": {
   "residential": 222.7,
   "business": 209.9,
   "government": 29.7,
   "agriculture": 6.9,
   "ev": 0,
   "other": 4
  },
  "series": [
   349,
   370.2,
   408.5,
   431.9,
   431.7,
   473.3
  ]
 },
 {
  "iso": "TH-36",
  "gwhPerYear": 993.2,
  "gwhPerDay": 2.721,
  "kwhPerPerson": 883,
  "byClass": {
   "residential": 469.4,
   "business": 459.8,
   "government": 40.9,
   "agriculture": 7.8,
   "ev": 0.2,
   "other": 15.1
  },
  "series": [
   811,
   880.2,
   907.7,
   932.9,
   941.8,
   993.2
  ]
 },
 {
  "iso": "TH-37",
  "gwhPerYear": 299.2,
  "gwhPerDay": 0.82,
  "kwhPerPerson": 795,
  "byClass": {
   "residential": 136.7,
   "business": 139.2,
   "government": 19,
   "agriculture": 1.5,
   "ev": 0.1,
   "other": 2.7
  },
  "series": [
   208.8,
   234.9,
   240,
   261.2,
   289.9,
   299.2
  ]
 },
 {
  "iso": "TH-38",
  "gwhPerYear": 401.1,
  "gwhPerDay": 1.099,
  "kwhPerPerson": 950,
  "byClass": {
   "residential": 178.6,
   "business": 176.7,
   "government": 39.5,
   "agriculture": 1.8,
   "ev": 0,
   "other": 4.4
  },
  "series": [
   288.3,
   309.6,
   136.7,
   146,
   364.7,
   401.1
  ]
 },
 {
  "iso": "TH-39",
  "gwhPerYear": 388.5,
  "gwhPerDay": 1.064,
  "kwhPerPerson": 762,
  "byClass": {
   "residential": 192.1,
   "business": 164.1,
   "government": 23.7,
   "agriculture": 4.2,
   "ev": 0,
   "other": 4.4
  },
  "series": [
   289.7,
   313.5,
   345.1,
   363.3,
   364.8,
   388.5
  ]
 },
 {
  "iso": "TH-40",
  "gwhPerYear": 2804,
  "gwhPerDay": 7.682,
  "kwhPerPerson": 1563,
  "byClass": {
   "residential": 1081.6,
   "business": 1597.4,
   "government": 89.9,
   "agriculture": 14.4,
   "ev": 0.3,
   "other": 20.3
  },
  "series": [
   2325.1,
   2497.1,
   2510.1,
   2600.5,
   2672.4,
   2804
  ]
 },
 {
  "iso": "TH-41",
  "gwhPerYear": 1825.9,
  "gwhPerDay": 5.002,
  "kwhPerPerson": 1168,
  "byClass": {
   "residential": 832.7,
   "business": 878.5,
   "government": 99.6,
   "agriculture": 1.6,
   "ev": 0.1,
   "other": 13.4
  },
  "series": [
   1432.9,
   1536,
   1618.8,
   1694.9,
   1715.6,
   1825.9
  ]
 },
 {
  "iso": "TH-42",
  "gwhPerYear": 637,
  "gwhPerDay": 1.745,
  "kwhPerPerson": 997,
  "byClass": {
   "residential": 282.6,
   "business": 301.7,
   "government": 42.5,
   "agriculture": 3.2,
   "ev": 0,
   "other": 6.9
  },
  "series": [
   475.6,
   508.5,
   561,
   589,
   603.4,
   637
  ]
 },
 {
  "iso": "TH-43",
  "gwhPerYear": 581.7,
  "gwhPerDay": 1.594,
  "kwhPerPerson": 1124,
  "byClass": {
   "residential": 289,
   "business": 231.7,
   "government": 45.1,
   "agriculture": 11.4,
   "ev": 0,
   "other": 4.5
  },
  "series": [
   443.8,
   479.5,
   716.1,
   760.6,
   570.6,
   581.7
  ]
 },
 {
  "iso": "TH-44",
  "gwhPerYear": 970.7,
  "gwhPerDay": 2.659,
  "kwhPerPerson": 1018,
  "byClass": {
   "residential": 431.2,
   "business": 479.6,
   "government": 40.8,
   "agriculture": 11.7,
   "ev": 0.1,
   "other": 7.2
  },
  "series": [
   742.6,
   803.2,
   858.6,
   901.6,
   902,
   970.7
  ]
 },
 {
  "iso": "TH-45",
  "gwhPerYear": 1156.5,
  "gwhPerDay": 3.168,
  "kwhPerPerson": 891,
  "byClass": {
   "residential": 555.8,
   "business": 511.1,
   "government": 57.2,
   "agriculture": 25.5,
   "ev": 0.2,
   "other": 6.7
  },
  "series": [
   895.5,
   962.9,
   1045,
   1094.4,
   1075.4,
   1156.5
  ]
 },
 {
  "iso": "TH-46",
  "gwhPerYear": 940.3,
  "gwhPerDay": 2.576,
  "kwhPerPerson": 962,
  "byClass": {
   "residential": 411.2,
   "business": 464,
   "government": 47.8,
   "agriculture": 8.5,
   "ev": 0.1,
   "other": 8.7
  },
  "series": [
   710.7,
   783.8,
   813.9,
   873,
   900.5,
   940.3
  ]
 },
 {
  "iso": "TH-47",
  "gwhPerYear": 953.4,
  "gwhPerDay": 2.612,
  "kwhPerPerson": 831,
  "byClass": {
   "residential": 480.9,
   "business": 397.6,
   "government": 63.9,
   "agriculture": 4.4,
   "ev": 0,
   "other": 6.5
  },
  "series": [
   689.2,
   759.6,
   823.7,
   888.9,
   898.5,
   953.4
  ]
 },
 {
  "iso": "TH-48",
  "gwhPerYear": 593.2,
  "gwhPerDay": 1.625,
  "kwhPerPerson": 827,
  "byClass": {
   "residential": 300.2,
   "business": 232.4,
   "government": 46.4,
   "agriculture": 9.2,
   "ev": 0,
   "other": 5.1
  },
  "series": [
   4625.7,
   468.4,
   529.5,
   567.3,
   556.6,
   593.2
  ]
 },
 {
  "iso": "TH-49",
  "gwhPerYear": 375.5,
  "gwhPerDay": 1.029,
  "kwhPerPerson": 1070,
  "byClass": {
   "residential": 145,
   "business": 204,
   "government": 19.6,
   "agriculture": 1.5,
   "ev": 0.1,
   "other": 5.3
  },
  "series": [
   290.2,
   314.7,
   338.8,
   362.3,
   360.5,
   375.5
  ]
 },
 {
  "iso": "TH-50",
  "gwhPerYear": 3806.8,
  "gwhPerDay": 10.43,
  "kwhPerPerson": 2133,
  "byClass": {
   "residential": 1527.6,
   "business": 2120.7,
   "government": 106.6,
   "agriculture": 14.1,
   "ev": 1,
   "other": 36.8
  },
  "series": [
   3256.7,
   3460.2,
   3438.8,
   3419.9,
   3547.5,
   3806.8
  ]
 },
 {
  "iso": "TH-51",
  "gwhPerYear": 1379.8,
  "gwhPerDay": 3.78,
  "kwhPerPerson": 3432,
  "byClass": {
   "residential": 284.2,
   "business": 1061.3,
   "government": 27.1,
   "agriculture": 3.3,
   "ev": 0,
   "other": 3.8
  },
  "series": [
   1350.6,
   1361.6,
   1357.7,
   1417.8,
   1400.3,
   1379.8
  ]
 },
 {
  "iso": "TH-52",
  "gwhPerYear": 1122.4,
  "gwhPerDay": 3.075,
  "kwhPerPerson": 1540,
  "byClass": {
   "residential": 394.9,
   "business": 664.3,
   "government": 51.2,
   "agriculture": 5.7,
   "ev": 0.5,
   "other": 5.8
  },
  "series": [
   942,
   990.2,
   1061.8,
   1084,
   1105.3,
   1122.4
  ]
 },
 {
  "iso": "TH-53",
  "gwhPerYear": 614.2,
  "gwhPerDay": 1.683,
  "kwhPerPerson": 1369,
  "byClass": {
   "residential": 278.3,
   "business": 237.9,
   "government": 32.7,
   "agriculture": 59.2,
   "ev": 0.2,
   "other": 5.9
  },
  "series": [
   490.1,
   526.5,
   563.5,
   566.8,
   569.1,
   614.2
  ]
 },
 {
  "iso": "TH-54",
  "gwhPerYear": 496.9,
  "gwhPerDay": 1.361,
  "kwhPerPerson": 1136,
  "byClass": {
   "residential": 231.6,
   "business": 223.9,
   "government": 34.4,
   "agriculture": 4.7,
   "ev": 0.2,
   "other": 2.2
  },
  "series": [
   403.2,
   419.2,
   463.2,
   472.7,
   469.3,
   496.9
  ]
 },
 {
  "iso": "TH-55",
  "gwhPerYear": 429.5,
  "gwhPerDay": 1.177,
  "kwhPerPerson": 901,
  "byClass": {
   "residential": 205.5,
   "business": 178.4,
   "government": 36.4,
   "agriculture": 4.4,
   "ev": 0,
   "other": 4.8
  },
  "series": [
   312.7,
   331.6,
   368.4,
   381.6,
   393.1,
   429.5
  ]
 },
 {
  "iso": "TH-56",
  "gwhPerYear": 463.2,
  "gwhPerDay": 1.269,
  "kwhPerPerson": 991,
  "byClass": {
   "residential": 214.7,
   "business": 218.3,
   "government": 24.8,
   "agriculture": 1.8,
   "ev": 0.1,
   "other": 3.5
  },
  "series": [
   367.3,
   391.9,
   414.2,
   427.9,
   435.2,
   463.2
  ]
 },
 {
  "iso": "TH-57",
  "gwhPerYear": 1617.4,
  "gwhPerDay": 4.431,
  "kwhPerPerson": 1249,
  "byClass": {
   "residential": 660.6,
   "business": 859.8,
   "government": 75.7,
   "agriculture": 6.1,
   "ev": 0.6,
   "other": 14.7
  },
  "series": [
   1277,
   1387.4,
   1426.3,
   1459.7,
   1549.1,
   1617.4
  ]
 },
 {
  "iso": "TH-58",
  "gwhPerYear": 168.1,
  "gwhPerDay": 0.461,
  "kwhPerPerson": 591,
  "byClass": {
   "residential": 74.3,
   "business": 83.2,
   "government": 8.7,
   "agriculture": 0.3,
   "ev": 0,
   "other": 1.6
  },
  "series": [
   127.7,
   135.7,
   145.7,
   151.9,
   158,
   168.1
  ]
 },
 {
  "iso": "TH-60",
  "gwhPerYear": 1766.4,
  "gwhPerDay": 4.84,
  "kwhPerPerson": 1698,
  "byClass": {
   "residential": 748.8,
   "business": 894.6,
   "government": 58.7,
   "agriculture": 30.1,
   "ev": 0.8,
   "other": 33.4
  },
  "series": [
   1449.1,
   1509.8,
   1583.5,
   1607.4,
   1639.8,
   1766.4
  ]
 },
 {
  "iso": "TH-61",
  "gwhPerYear": 412.3,
  "gwhPerDay": 1.13,
  "kwhPerPerson": 1265,
  "byClass": {
   "residential": 214.4,
   "business": 155.9,
   "government": 30.8,
   "agriculture": 7.2,
   "ev": 0,
   "other": 3.8
  },
  "series": [
   295.1,
   310.6,
   343.8,
   366.6,
   379.6,
   412.3
  ]
 },
 {
  "iso": "TH-62",
  "gwhPerYear": 1136.8,
  "gwhPerDay": 3.114,
  "kwhPerPerson": 1592,
  "byClass": {
   "residential": 429.4,
   "business": 625.2,
   "government": 61,
   "agriculture": 15.2,
   "ev": 0.3,
   "other": 5.7
  },
  "series": [
   1026.6,
   1045.2,
   1083.5,
   1114.4,
   1116.8,
   1136.8
  ]
 },
 {
  "iso": "TH-63",
  "gwhPerYear": 860.8,
  "gwhPerDay": 2.358,
  "kwhPerPerson": 1284,
  "byClass": {
   "residential": 292.4,
   "business": 512.8,
   "government": 43.7,
   "agriculture": 3,
   "ev": 0.2,
   "other": 8.7
  },
  "series": [
   622.3,
   674.5,
   723,
   716.6,
   804.6,
   860.8
  ]
 },
 {
  "iso": "TH-64",
  "gwhPerYear": 682.2,
  "gwhPerDay": 1.869,
  "kwhPerPerson": 1160,
  "byClass": {
   "residential": 354.8,
   "business": 263.9,
   "government": 47.8,
   "agriculture": 12.2,
   "ev": 0.1,
   "other": 3.4
  },
  "series": [
   524.3,
   563.1,
   612.5,
   624.7,
   622.2,
   682.2
  ]
 },
 {
  "iso": "TH-65",
  "gwhPerYear": 1617,
  "gwhPerDay": 4.43,
  "kwhPerPerson": 1903,
  "byClass": {
   "residential": 634.3,
   "business": 860.9,
   "government": 89,
   "agriculture": 24.6,
   "ev": 0.4,
   "other": 7.7
  },
  "series": [
   1258.7,
   1329.1,
   1447.7,
   1450.8,
   1508.8,
   1617
  ]
 },
 {
  "iso": "TH-66",
  "gwhPerYear": 861.1,
  "gwhPerDay": 2.359,
  "kwhPerPerson": 1618,
  "byClass": {
   "residential": 370.2,
   "business": 411.1,
   "government": 41.9,
   "agriculture": 32.7,
   "ev": 0.1,
   "other": 5.2
  },
  "series": [
   611.6,
   642.7,
   706.4,
   743.6,
   736,
   861.1
  ]
 },
 {
  "iso": "TH-67",
  "gwhPerYear": 1233.1,
  "gwhPerDay": 3.378,
  "kwhPerPerson": 1256,
  "byClass": {
   "residential": 523,
   "business": 649.3,
   "government": 49.2,
   "agriculture": 0.8,
   "ev": 0.4,
   "other": 10.4
  },
  "series": [
   973,
   1034.6,
   1107.6,
   1115.5,
   1143.6,
   1233.1
  ]
 },
 {
  "iso": "TH-70",
  "gwhPerYear": 2744.4,
  "gwhPerDay": 7.519,
  "kwhPerPerson": 3157,
  "byClass": {
   "residential": 796.1,
   "business": 1844.3,
   "government": 84.8,
   "agriculture": 1.4,
   "ev": 0.2,
   "other": 17.6
  },
  "series": [
   2535,
   2469.8,
   2468.4,
   2584.4,
   2791,
   2744.4
  ]
 },
 {
  "iso": "TH-71",
  "gwhPerYear": 2266.5,
  "gwhPerDay": 6.209,
  "kwhPerPerson": 2541,
  "byClass": {
   "residential": 696.4,
   "business": 1463,
   "government": 83.4,
   "agriculture": 13.2,
   "ev": 0.3,
   "other": 10.2
  },
  "series": [
   1836.5,
   1836,
   1836.4,
   1850.7,
   2051.7,
   2266.5
  ]
 },
 {
  "iso": "TH-72",
  "gwhPerYear": 1720.3,
  "gwhPerDay": 4.713,
  "kwhPerPerson": 2051,
  "byClass": {
   "residential": 667.1,
   "business": 956.5,
   "government": 84.1,
   "agriculture": 3.1,
   "ev": 0.1,
   "other": 9.3
  },
  "series": [
   1375.1,
   1473.4,
   1542.4,
   1566.9,
   1601.9,
   1720.3
  ]
 },
 {
  "iso": "TH-73",
  "gwhPerYear": 5043.6,
  "gwhPerDay": 13.818,
  "kwhPerPerson": 5478,
  "byClass": {
   "residential": 1079.9,
   "business": 3799.4,
   "government": 134.2,
   "agriculture": 0.8,
   "ev": 3.4,
   "other": 25.8
  },
  "series": [
   429.4,
   4768.8,
   6230.2,
   6292.9,
   4950,
   5043.6
  ]
 },
 {
  "iso": "TH-74",
  "gwhPerYear": 8232.2,
  "gwhPerDay": 22.554,
  "kwhPerPerson": 14043,
  "byClass": {
   "residential": 855.8,
   "business": 7251.2,
   "government": 94.8,
   "agriculture": 0,
   "ev": 1.6,
   "other": 28.8
  },
  "series": [
   8259.3,
   8328.5,
   6768.3,
   6959.8,
   8529,
   8232.2
  ]
 },
 {
  "iso": "TH-75",
  "gwhPerYear": 539.8,
  "gwhPerDay": 1.479,
  "kwhPerPerson": 2811,
  "byClass": {
   "residential": 182.5,
   "business": 335.6,
   "government": 18,
   "agriculture": 0,
   "ev": 0,
   "other": 3.7
  },
  "series": [
   425.8,
   452.3,
   474.9,
   487.2,
   509.9,
   539.8
  ]
 },
 {
  "iso": "TH-76",
  "gwhPerYear": 1571.9,
  "gwhPerDay": 4.307,
  "kwhPerPerson": 3255,
  "byClass": {
   "residential": 459.1,
   "business": 1027.3,
   "government": 71.8,
   "agriculture": 3.6,
   "ev": 0.6,
   "other": 9.4
  },
  "series": [
   1517.1,
   1495.7,
   1496.5,
   1541.9,
   1604.1,
   1571.9
  ]
 },
 {
  "iso": "TH-77",
  "gwhPerYear": 1745.8,
  "gwhPerDay": 4.783,
  "kwhPerPerson": 3170,
  "byClass": {
   "residential": 569.4,
   "business": 1090.5,
   "government": 68.8,
   "agriculture": 0.1,
   "ev": 0.4,
   "other": 16.5
  },
  "series": [
   1725.3,
   1719.3,
   1632.1,
   1682.7,
   1724.3,
   1745.8
  ]
 },
 {
  "iso": "TH-80",
  "gwhPerYear": 2038,
  "gwhPerDay": 5.584,
  "kwhPerPerson": 1314,
  "byClass": {
   "residential": 962.1,
   "business": 985,
   "government": 74.4,
   "agriculture": 1.9,
   "ev": 0.3,
   "other": 14.4
  },
  "series": [
   1727.4,
   1779.6,
   1876.7,
   1934.4,
   1962.8,
   2038
  ]
 },
 {
  "iso": "TH-81",
  "gwhPerYear": 950,
  "gwhPerDay": 2.603,
  "kwhPerPerson": 1988,
  "byClass": {
   "residential": 364,
   "business": 541,
   "government": 35.5,
   "agriculture": 0,
   "ev": 0.1,
   "other": 9.3
  },
  "series": [
   874.3,
   903.5,
   837.9,
   790.1,
   867.4,
   950
  ]
 },
 {
  "iso": "TH-82",
  "gwhPerYear": 675.4,
  "gwhPerDay": 1.851,
  "kwhPerPerson": 2518,
  "byClass": {
   "residential": 199.6,
   "business": 440.1,
   "government": 30.4,
   "agriculture": 0,
   "ev": 0.1,
   "other": 5.2
  },
  "series": [
   633.1,
   647.2,
   593.8,
   575.2,
   628.9,
   675.4
  ]
 },
 {
  "iso": "TH-83",
  "gwhPerYear": 2935.3,
  "gwhPerDay": 8.042,
  "kwhPerPerson": 7009,
  "byClass": {
   "residential": 810.9,
   "business": 2039.1,
   "government": 41.5,
   "agriculture": 0,
   "ev": 0.4,
   "other": 43.5
  },
  "series": [
   2855.5,
   2991.7,
   2251.5,
   1950.1,
   2386.6,
   2935.3
  ]
 },
 {
  "iso": "TH-84",
  "gwhPerYear": 3426.2,
  "gwhPerDay": 9.387,
  "kwhPerPerson": 3191,
  "byClass": {
   "residential": 1002.2,
   "business": 2342.1,
   "government": 58.1,
   "agriculture": 0.5,
   "ev": 0.5,
   "other": 22.7
  },
  "series": [
   2956.2,
   3049.2,
   2938.5,
   2911.3,
   3066.3,
   3426.2
  ]
 },
 {
  "iso": "TH-85",
  "gwhPerYear": 401.3,
  "gwhPerDay": 1.099,
  "kwhPerPerson": 2064,
  "byClass": {
   "residential": 126.5,
   "business": 253.3,
   "government": 17.7,
   "agriculture": 0,
   "ev": 0.1,
   "other": 3.7
  },
  "series": [
   392.1,
   387.3,
   412.1,
   398.3,
   400.2,
   401.3
  ]
 },
 {
  "iso": "TH-86",
  "gwhPerYear": 1066.7,
  "gwhPerDay": 2.922,
  "kwhPerPerson": 2095,
  "byClass": {
   "residential": 433.3,
   "business": 587.9,
   "government": 34.6,
   "agriculture": 1.2,
   "ev": 0.2,
   "other": 9.4
  },
  "series": [
   833.6,
   877.8,
   910.7,
   951.2,
   973.5,
   1066.7
  ]
 },
 {
  "iso": "TH-90",
  "gwhPerYear": 3662.6,
  "gwhPerDay": 10.034,
  "kwhPerPerson": 2564,
  "byClass": {
   "residential": 1041,
   "business": 2490.3,
   "government": 98.8,
   "agriculture": 2.6,
   "ev": 0.2,
   "other": 29.6
  },
  "series": [
   3553.3,
   3527.1,
   3567,
   3608,
   3614.6,
   3662.6
  ]
 },
 {
  "iso": "TH-91",
  "gwhPerYear": 401,
  "gwhPerDay": 1.099,
  "kwhPerPerson": 1237,
  "byClass": {
   "residential": 156.4,
   "business": 207.5,
   "government": 35.1,
   "agriculture": 0,
   "ev": 0,
   "other": 1.9
  },
  "series": [
   343.9,
   347.4,
   373.4,
   385.9,
   393.4,
   401
  ]
 },
 {
  "iso": "TH-92",
  "gwhPerYear": 1092.5,
  "gwhPerDay": 2.993,
  "kwhPerPerson": 1705,
  "byClass": {
   "residential": 389.5,
   "business": 644.2,
   "government": 52.8,
   "agriculture": 0.1,
   "ev": 0.1,
   "other": 5.8
  },
  "series": [
   875.6,
   882.6,
   1000.6,
   1043.6,
   1056.3,
   1092.5
  ]
 },
 {
  "iso": "TH-93",
  "gwhPerYear": 586,
  "gwhPerDay": 1.605,
  "kwhPerPerson": 1120,
  "byClass": {
   "residential": 294.8,
   "business": 245.8,
   "government": 38.2,
   "agriculture": 2.8,
   "ev": 0.1,
   "other": 4.3
  },
  "series": [
   489.9,
   497.8,
   538.1,
   560.4,
   567.4,
   586
  ]
 },
 {
  "iso": "TH-94",
  "gwhPerYear": 595.7,
  "gwhPerDay": 1.632,
  "kwhPerPerson": 820,
  "byClass": {
   "residential": 262,
   "business": 287.4,
   "government": 40.4,
   "agriculture": 0.1,
   "ev": 0,
   "other": 5.7
  },
  "series": [
   497.8,
   501.7,
   548.5,
   571.4,
   581.8,
   595.7
  ]
 },
 {
  "iso": "TH-95",
  "gwhPerYear": 505.6,
  "gwhPerDay": 1.385,
  "kwhPerPerson": 939,
  "byClass": {
   "residential": 219.5,
   "business": 241,
   "government": 39.6,
   "agriculture": 0.1,
   "ev": 0,
   "other": 5.4
  },
  "series": [
   407.2,
   417.8,
   457.6,
   473.9,
   491.3,
   505.6
  ]
 },
 {
  "iso": "TH-96",
  "gwhPerYear": 524.4,
  "gwhPerDay": 1.437,
  "kwhPerPerson": 652,
  "byClass": {
   "residential": 265.5,
   "business": 213.6,
   "government": 41.4,
   "agriculture": 0.1,
   "ev": 0,
   "other": 3.9
  },
  "series": [
   413.3,
   423.3,
   470.6,
   490.3,
   505.5,
   524.4
  ]
 }
];
