// GENERATED by scripts/fetch-protected-areas.mjs — do not edit.
//
// National park, wildlife sanctuary and reserve coverage per province.
//
// Measured by scan-converting both the parks and the province boundaries onto
// a shared 555 m grid and counting the overlap, rather than intersecting
// polygons. Accuracy is bounded by the cell size; the build prints rasterised
// area against polygon area for every province so that bound is visible.
//
// What this is for: land inside a national park is not available for a solar
// farm, and an allocation that ignores that will site capacity where it cannot
// be built.
//
// Data © OpenStreetMap contributors, ODbL. OSM's protected-area coverage of
// Thailand is good but not authoritative — treat these as close, not exact.

export interface ProvinceProtected {
  iso: string;
  protectedKm2: number;
  /** Share of the province inside a protected area, 0-1. */
  protectedFrac: number;
  /** Province area as the raster saw it, for judging the figure above. */
  rasterKm2: number;
}

export const PROVINCE_PROTECTED: ProvinceProtected[] = [
 {
  "iso": "TH-10",
  "protectedKm2": 0,
  "protectedFrac": 0,
  "rasterKm2": 1567
 },
 {
  "iso": "TH-11",
  "protectedKm2": 15,
  "protectedFrac": 0.016,
  "rasterKm2": 968
 },
 {
  "iso": "TH-12",
  "protectedKm2": 0,
  "protectedFrac": 0,
  "rasterKm2": 636
 },
 {
  "iso": "TH-13",
  "protectedKm2": 0,
  "protectedFrac": 0,
  "rasterKm2": 1516
 },
 {
  "iso": "TH-14",
  "protectedKm2": 3,
  "protectedFrac": 0.001,
  "rasterKm2": 2564
 },
 {
  "iso": "TH-15",
  "protectedKm2": 0,
  "protectedFrac": 0,
  "rasterKm2": 944
 },
 {
  "iso": "TH-16",
  "protectedKm2": 322,
  "protectedFrac": 0.05,
  "rasterKm2": 6478
 },
 {
  "iso": "TH-17",
  "protectedKm2": 0,
  "protectedFrac": 0,
  "rasterKm2": 820
 },
 {
  "iso": "TH-18",
  "protectedKm2": 1,
  "protectedFrac": 0,
  "rasterKm2": 2507
 },
 {
  "iso": "TH-19",
  "protectedKm2": 259,
  "protectedFrac": 0.076,
  "rasterKm2": 3421
 },
 {
  "iso": "TH-20",
  "protectedKm2": 267,
  "protectedFrac": 0.059,
  "rasterKm2": 4511
 },
 {
  "iso": "TH-21",
  "protectedKm2": 117,
  "protectedFrac": 0.032,
  "rasterKm2": 3673
 },
 {
  "iso": "TH-22",
  "protectedKm2": 1620,
  "protectedFrac": 0.253,
  "rasterKm2": 6393
 },
 {
  "iso": "TH-23",
  "protectedKm2": 357,
  "protectedFrac": 0.125,
  "rasterKm2": 2869
 },
 {
  "iso": "TH-24",
  "protectedKm2": 651,
  "protectedFrac": 0.126,
  "rasterKm2": 5156
 },
 {
  "iso": "TH-25",
  "protectedKm2": 1492,
  "protectedFrac": 0.296,
  "rasterKm2": 5039
 },
 {
  "iso": "TH-26",
  "protectedKm2": 578,
  "protectedFrac": 0.27,
  "rasterKm2": 2141
 },
 {
  "iso": "TH-27",
  "protectedKm2": 1088,
  "protectedFrac": 0.161,
  "rasterKm2": 6771
 },
 {
  "iso": "TH-30",
  "protectedKm2": 2316,
  "protectedFrac": 0.112,
  "rasterKm2": 20718
 },
 {
  "iso": "TH-31",
  "protectedKm2": 693,
  "protectedFrac": 0.069,
  "rasterKm2": 10047
 },
 {
  "iso": "TH-32",
  "protectedKm2": 499,
  "protectedFrac": 0.057,
  "rasterKm2": 8781
 },
 {
  "iso": "TH-33",
  "protectedKm2": 769,
  "protectedFrac": 0.087,
  "rasterKm2": 8860
 },
 {
  "iso": "TH-34",
  "protectedKm2": 1824,
  "protectedFrac": 0.118,
  "rasterKm2": 15451
 },
 {
  "iso": "TH-35",
  "protectedKm2": 58,
  "protectedFrac": 0.014,
  "rasterKm2": 4089
 },
 {
  "iso": "TH-36",
  "protectedKm2": 3225,
  "protectedFrac": 0.256,
  "rasterKm2": 12608
 },
 {
  "iso": "TH-37",
  "protectedKm2": 89,
  "protectedFrac": 0.027,
  "rasterKm2": 3263
 },
 {
  "iso": "TH-38",
  "protectedKm2": 218,
  "protectedFrac": 0.055,
  "rasterKm2": 3980
 },
 {
  "iso": "TH-39",
  "protectedKm2": 239,
  "protectedFrac": 0.059,
  "rasterKm2": 4065
 },
 {
  "iso": "TH-40",
  "protectedKm2": 887,
  "protectedFrac": 0.084,
  "rasterKm2": 10594
 },
 {
  "iso": "TH-41",
  "protectedKm2": 300,
  "protectedFrac": 0.027,
  "rasterKm2": 11041
 },
 {
  "iso": "TH-42",
  "protectedKm2": 1763,
  "protectedFrac": 0.168,
  "rasterKm2": 10483
 },
 {
  "iso": "TH-43",
  "protectedKm2": 0,
  "protectedFrac": 0,
  "rasterKm2": 3262
 },
 {
  "iso": "TH-44",
  "protectedKm2": 1,
  "protectedFrac": 0,
  "rasterKm2": 5603
 },
 {
  "iso": "TH-45",
  "protectedKm2": 64,
  "protectedFrac": 0.008,
  "rasterKm2": 7812
 },
 {
  "iso": "TH-46",
  "protectedKm2": 505,
  "protectedFrac": 0.073,
  "rasterKm2": 6876
 },
 {
  "iso": "TH-47",
  "protectedKm2": 1127,
  "protectedFrac": 0.118,
  "rasterKm2": 9516
 },
 {
  "iso": "TH-48",
  "protectedKm2": 226,
  "protectedFrac": 0.041,
  "rasterKm2": 5568
 },
 {
  "iso": "TH-49",
  "protectedKm2": 968,
  "protectedFrac": 0.236,
  "rasterKm2": 4107
 },
 {
  "iso": "TH-50",
  "protectedKm2": 6907,
  "protectedFrac": 0.312,
  "rasterKm2": 22146
 },
 {
  "iso": "TH-51",
  "protectedKm2": 1259,
  "protectedFrac": 0.281,
  "rasterKm2": 4476
 },
 {
  "iso": "TH-52",
  "protectedKm2": 2876,
  "protectedFrac": 0.23,
  "rasterKm2": 12480
 },
 {
  "iso": "TH-53",
  "protectedKm2": 2982,
  "protectedFrac": 0.377,
  "rasterKm2": 7902
 },
 {
  "iso": "TH-54",
  "protectedKm2": 1374,
  "protectedFrac": 0.212,
  "rasterKm2": 6481
 },
 {
  "iso": "TH-55",
  "protectedKm2": 3889,
  "protectedFrac": 0.32,
  "rasterKm2": 12168
 },
 {
  "iso": "TH-56",
  "protectedKm2": 2503,
  "protectedFrac": 0.405,
  "rasterKm2": 6185
 },
 {
  "iso": "TH-57",
  "protectedKm2": 1431,
  "protectedFrac": 0.124,
  "rasterKm2": 11559
 },
 {
  "iso": "TH-58",
  "protectedKm2": 6287,
  "protectedFrac": 0.493,
  "rasterKm2": 12750
 },
 {
  "iso": "TH-60",
  "protectedKm2": 641,
  "protectedFrac": 0.067,
  "rasterKm2": 9534
 },
 {
  "iso": "TH-61",
  "protectedKm2": 2739,
  "protectedFrac": 0.413,
  "rasterKm2": 6627
 },
 {
  "iso": "TH-62",
  "protectedKm2": 1541,
  "protectedFrac": 0.18,
  "rasterKm2": 8555
 },
 {
  "iso": "TH-63",
  "protectedKm2": 8328,
  "protectedFrac": 0.468,
  "rasterKm2": 17788
 },
 {
  "iso": "TH-64",
  "protectedKm2": 842,
  "protectedFrac": 0.126,
  "rasterKm2": 6671
 },
 {
  "iso": "TH-65",
  "protectedKm2": 2892,
  "protectedFrac": 0.275,
  "rasterKm2": 10506
 },
 {
  "iso": "TH-66",
  "protectedKm2": 2,
  "protectedFrac": 0,
  "rasterKm2": 3965
 },
 {
  "iso": "TH-67",
  "protectedKm2": 2598,
  "protectedFrac": 0.21,
  "rasterKm2": 12353
 },
 {
  "iso": "TH-70",
  "protectedKm2": 836,
  "protectedFrac": 0.161,
  "rasterKm2": 5206
 },
 {
  "iso": "TH-71",
  "protectedKm2": 10316,
  "protectedFrac": 0.532,
  "rasterKm2": 19392
 },
 {
  "iso": "TH-72",
  "protectedKm2": 338,
  "protectedFrac": 0.062,
  "rasterKm2": 5419
 },
 {
  "iso": "TH-73",
  "protectedKm2": 0,
  "protectedFrac": 0,
  "rasterKm2": 2142
 },
 {
  "iso": "TH-74",
  "protectedKm2": 1,
  "protectedFrac": 0.001,
  "rasterKm2": 853
 },
 {
  "iso": "TH-75",
  "protectedKm2": 3,
  "protectedFrac": 0.008,
  "rasterKm2": 421
 },
 {
  "iso": "TH-76",
  "protectedKm2": 2792,
  "protectedFrac": 0.453,
  "rasterKm2": 6159
 },
 {
  "iso": "TH-77",
  "protectedKm2": 1922,
  "protectedFrac": 0.298,
  "rasterKm2": 6458
 },
 {
  "iso": "TH-80",
  "protectedKm2": 1774,
  "protectedFrac": 0.179,
  "rasterKm2": 9907
 },
 {
  "iso": "TH-81",
  "protectedKm2": 767,
  "protectedFrac": 0.136,
  "rasterKm2": 5620
 },
 {
  "iso": "TH-82",
  "protectedKm2": 878,
  "protectedFrac": 0.187,
  "rasterKm2": 4695
 },
 {
  "iso": "TH-83",
  "protectedKm2": 41,
  "protectedFrac": 0.077,
  "rasterKm2": 538
 },
 {
  "iso": "TH-84",
  "protectedKm2": 3787,
  "protectedFrac": 0.29,
  "rasterKm2": 13073
 },
 {
  "iso": "TH-85",
  "protectedKm2": 1736,
  "protectedFrac": 0.53,
  "rasterKm2": 3275
 },
 {
  "iso": "TH-86",
  "protectedKm2": 1251,
  "protectedFrac": 0.208,
  "rasterKm2": 6020
 },
 {
  "iso": "TH-90",
  "protectedKm2": 1228,
  "protectedFrac": 0.159,
  "rasterKm2": 7742
 },
 {
  "iso": "TH-91",
  "protectedKm2": 867,
  "protectedFrac": 0.301,
  "rasterKm2": 2882
 },
 {
  "iso": "TH-92",
  "protectedKm2": 1158,
  "protectedFrac": 0.224,
  "rasterKm2": 5175
 },
 {
  "iso": "TH-93",
  "protectedKm2": 1419,
  "protectedFrac": 0.368,
  "rasterKm2": 3859
 },
 {
  "iso": "TH-94",
  "protectedKm2": 40,
  "protectedFrac": 0.02,
  "rasterKm2": 1971
 },
 {
  "iso": "TH-95",
  "protectedKm2": 453,
  "protectedFrac": 0.101,
  "rasterKm2": 4475
 },
 {
  "iso": "TH-96",
  "protectedKm2": 1000,
  "protectedFrac": 0.223,
  "rasterKm2": 4485
 }
];

export interface AmphoeProtected {
  /** OSM relation id — the same key AMPHOE uses. */
  id: string;
  iso: string;
  /** OSM's English name, so a consumer can join without loading geometry. */
  en: string;
  protectedKm2: number;
  protectedFrac: number;
  rasterKm2: number;
}

/**
 * Phetchaburi's eight, and only those.
 *
 * districts.ts needs them at module load to work out how much of each district
 * can be built on, and it cannot import the full 931 without dragging 94 kB
 * into the Map tab for every visitor, whether or not they ever open a
 * province. The rest live in protectedAmphoe.ts and are fetched with the
 * geometry when someone actually zooms in.
 */
export const PHETCHABURI_AMPHOE_PROTECTED: AmphoeProtected[] = [
 {
  "id": "18934639",
  "iso": "TH-76",
  "en": "Khao Yoi",
  "protectedFrac": 0,
  "protectedKm2": 0,
  "rasterKm2": 316
 },
 {
  "id": "18934681",
  "iso": "TH-76",
  "en": "Ban Lat",
  "protectedFrac": 0,
  "protectedKm2": 0,
  "rasterKm2": 261
 },
 {
  "id": "18934757",
  "iso": "TH-76",
  "en": "Nong Ya Plong",
  "protectedFrac": 0.63,
  "protectedKm2": 774,
  "rasterKm2": 1228
 },
 {
  "id": "18934877",
  "iso": "TH-76",
  "en": "Kaeng Krachan",
  "protectedFrac": 0.766,
  "protectedKm2": 1974,
  "rasterKm2": 2577
 },
 {
  "id": "18934935",
  "iso": "TH-76",
  "en": "Cha-am",
  "protectedFrac": 0.011,
  "protectedKm2": 6,
  "rasterKm2": 518
 },
 {
  "id": "18935050",
  "iso": "TH-76",
  "en": "Tha Yang",
  "protectedFrac": 0.05,
  "protectedKm2": 38,
  "rasterKm2": 768
 },
 {
  "id": "18935190",
  "iso": "TH-76",
  "en": "Mueang Phetchaburi",
  "protectedFrac": 0.001,
  "protectedKm2": 0,
  "rasterKm2": 290
 },
 {
  "id": "18935383",
  "iso": "TH-76",
  "en": "Ban Laem",
  "protectedFrac": 0,
  "protectedKm2": 0,
  "rasterKm2": 200
 }
];
