// GENERATED by scripts/build-thailand-geo.mjs — do not edit.

/** One amphoe, projected into the shared nationwide viewBox. */
export interface AmphoeGeo {
  /** OSM relation id — stable, and the join key back to the source. */
  id: string;
  th: string;
  en: string;
  /** Area in km², from the boundary itself. */
  km2: number;
  /** Label anchor, in viewBox units. */
  centroid: [number, number];
  /** [lon, lat] in degrees — for asking a service about this place. */
  lonLat: [number, number];
  path: string;
}

export interface ProvinceGeo {
  /** ISO 3166-2 code, e.g. "TH-76". */
  iso: string;
  th: string;
  en: string;
  /** Wikidata id, for joining population and other attributes. */
  wikidata: string | null;
  /** Area computed from the boundary. */
  km2: number;
  /** Area on record, for comparison. Where the two disagree by more than a few
   *  per cent, the boundary data is incomplete — Phichit is missing อำเภอสามง่าม,
   *  which has no admin_level=6 relation in OSM at all. */
  officialKm2: number | null;
  population: number | null;
  populationYear: number | null;
  amphoeCount: number;
  /** [minX, minY, maxX, maxY] in viewBox units — the viewBox to zoom to. */
  bbox: [number, number, number, number];
  /** In viewBox units — for placing a label. */
  centroid: [number, number];
  /** [lon, lat] in degrees — for asking a service about this place. */
  lonLat: [number, number];
  /** Province outline: the amphoe with their shared borders dissolved away. */
  outline: string;
}
